const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
async function runProjectVisuals({ win, origin, output, pressEnter }) {
  const wc = win.webContents, js = async code => {
    try { return await wc.executeJavaScript(code); }
    catch (error) { console.error('Project expression:', code); throw error; }
  };
  const wait = async code => { for (let i = 0; i < 100; i++) { if (await js(code)) return; await new Promise(r => setTimeout(r, 50)); } throw Error(`Project check timed out: ${code}`); };
  await wait(`!!document.querySelector('[data-workspace-ready="true"] textarea[aria-label="Prompt"]')`);
  const settingsDialog = '[role="dialog"][aria-label^="Workspace settings"]';
  const openSettings = async () => {
    await wait(`!!document.querySelector('[data-workspace-trigger]')`);
    await js(`document.querySelector('[data-workspace-trigger]').click()`);
    await wait(`!!document.querySelector('[data-workspace-menu]')`);
    await wait(`!!Array.from(document.querySelectorAll('[data-workspace-menu] button')).find(b=>b.textContent.includes('Project settings'))`);
    await js(`Array.from(document.querySelectorAll('[data-workspace-menu] button')).find(b=>b.textContent.includes('Project settings')).click()`);
    await wait(`!!document.querySelector('${settingsDialog} [aria-label="Auto-approve tools"]')`);
  };
  await js(`window.projectRequests=[];const projectFetch=window.fetch;window.fetch=(input,options)=>{window.projectRequests.push(String(input));return projectFetch(input,options);};true`);
  await openSettings();
  const originalSettings = await js(`(()=>{const d=document.querySelector('${settingsDialog}');return {name:d.querySelector('input').value,yolo:d.querySelector('[aria-label="Auto-approve tools"]').getAttribute('aria-checked'),mcp:d.querySelector('[aria-label="Start MCP servers"]').getAttribute('aria-checked')}})()`);
  await js(`(()=>{const d=document.querySelector('${settingsDialog}'),e=d.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'cancel-probe');e.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('[aria-label="Auto-approve tools"]').click()})()`);
  assert.ok(await js(`!!document.querySelector('${settingsDialog}')`), 'Auto-approve switch keeps Project Settings open');
  assert.notEqual(await js(`document.querySelector('[aria-label="Auto-approve tools"]').getAttribute('aria-checked')`), originalSettings.yolo);
  await js(`Array.from(document.querySelectorAll('${settingsDialog} button')).find(b=>b.textContent==='Cancel').click()`);
  await wait(`!document.querySelector('${settingsDialog}')`);
  await openSettings();
  assert.deepEqual(await js(`(()=>{const d=document.querySelector('${settingsDialog}');return {name:d.querySelector('input').value,yolo:d.querySelector('[aria-label="Auto-approve tools"]').getAttribute('aria-checked')}})()`), { name: originalSettings.name, yolo: originalSettings.yolo }, 'Cancel discards the settings draft');
  await js(`(()=>{const d=document.querySelector('${settingsDialog}'),e=d.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'settings-save-probe');e.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('[aria-label="Auto-approve tools"]').click()})()`);
  assert.ok(await js(`!!document.querySelector('${settingsDialog}')`), 'Auto-approve switch still keeps the dialog open before Save');
  await js(`document.querySelector('[aria-label="Start MCP servers"]').click()`);
  assert.ok(await js(`!!document.querySelector('${settingsDialog}')`), 'MCP switch keeps Project Settings open');
  await js(`Array.from(document.querySelectorAll('${settingsDialog} button')).find(b=>b.textContent==='Save').click()`);
  await wait(`!document.querySelector('${settingsDialog}')`);
  await openSettings();
  assert.deepEqual(await js(`(()=>{const d=document.querySelector('${settingsDialog}');return {name:d.querySelector('input').value,yolo:d.querySelector('[aria-label="Auto-approve tools"]').getAttribute('aria-checked'),mcp:d.querySelector('[aria-label="Start MCP servers"]').getAttribute('aria-checked')}})()`), { name: 'settings-save-probe', yolo: originalSettings.yolo === 'true' ? 'false' : 'true', mcp: originalSettings.mcp === 'true' ? 'false' : 'true' }, 'Save persists the complete settings draft');
  await js(`(()=>{const d=document.querySelector('${settingsDialog}'),e=d.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(originalSettings.name)});e.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('[aria-label="Auto-approve tools"]').click()})()`);
  await js(`document.querySelector('[aria-label="Start MCP servers"]').click()`);
  await js(`Array.from(document.querySelectorAll('${settingsDialog} button')).find(b=>b.textContent==='Save').click()`);
  await wait(`!document.querySelector('${settingsDialog}')`);
  await js(`document.querySelector('button[aria-label="Projects"]').click()`);
  await wait(`!!document.querySelector('[aria-label="Search projects"]')`);
  await js(`(()=>{const e=document.querySelector('[aria-label="Search projects"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'folder-42');e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  await wait(`document.querySelectorAll('[data-project-path]').length===1`);
  assert.equal(await js(`document.querySelector('[data-project-path]').dataset.projectPath`), '/demo/folder-42');
  fs.writeFileSync(path.join(output, 'projects.png'), (await wc.capturePage()).toPNG());
  await js(`document.querySelector('[data-project-path] button').click()`);
  await wait(`document.querySelector('[data-conversation-project]')?.textContent==='/demo/folder-42'`);
  await wait(`window.projectRequests.some(p=>p.includes('/api/sessions?')&&p.includes('root=%2Fdemo%2Ffolder-42')&&p.includes('scope=local'))`);
  const before = await js(`document.querySelectorAll('[aria-label="Close tab"]').length`);
  await js(`document.querySelector('button[aria-label="Projects"]').click()`);
  await wait(`!!document.querySelector('[data-project-path="/demo/folder-42"]')`);
  await js(`document.querySelector('[data-project-path="/demo/folder-42"] button:last-child').click()`);
  await wait(`document.querySelector('[data-workspace-trigger] [title]')?.title.includes('/demo/folder-42')`);
  assert.equal(await js(`document.querySelectorAll('[aria-label="Close tab"]').length`), before + 1, 'New project chat creates exactly one tab');
  await js(`document.querySelector('button[aria-label="Projects"]').click()`);
  await wait(`!!document.querySelector('[data-project-path="/demo/folder-43"]')`);
  await js(`document.querySelector('[data-project-path="/demo/folder-43"] button:last-child').click()`);
  await wait(`document.querySelector('[data-workspace-trigger] [title]')?.title.includes('/demo/folder-43')`);
  await js(`document.querySelector('[aria-label="Close tab"]').parentElement.querySelector('button[aria-pressed]').click()`);
  await wait(`document.querySelector('[data-workspace-trigger] [title]')?.title.includes('/demo/folder-42')`);
  await js(`document.querySelector('button[aria-label="New chat"]').click()`);
  await wait(`document.querySelector('[data-workspace-trigger] [title]')?.title.includes('/demo/folder-42')`);
  await js(`document.querySelector('button[aria-label="Review workspace changes"]').click()`);
  await wait(`!!document.querySelector('[aria-label="Workspace changes"]')`);
  await wait(`document.body.textContent.includes('palette.css')`);
  await wait(`!!document.querySelector('button[aria-label="Files"]')`);
  await js(`document.querySelector('button[aria-label="Files"]').click()`);
  await wait(`!!document.querySelector('[aria-label="Workspace files"]')`);
  assert.equal(await js(`!!document.querySelector('[aria-label="Workspace changes"]')`), false);
  await js(`window.folderFetchCount=0;window.releaseFolderFetch=[];const folderBaseFetch=window.fetch;window.fetch=(input,options)=>{if(String(input).includes('/api/workspaces')){window.folderFetchCount+=1;const reply=()=>new Response(JSON.stringify({path:'/demo',parent:'/',git:false,home:'/demo',default:'/demo',entries:[{name:'apps',path:'/demo/apps',git:false}]}),{headers:{'content-type':'application/json'}});if(window.folderFetchCount===1)return Promise.resolve(reply());return new Promise(resolve=>window.releaseFolderFetch.push(()=>resolve(reply())));}return folderBaseFetch(input,options);};true`);
  await js(`document.querySelector('button[aria-label="Open folder…"]').click()`);
  await wait(`document.querySelector('[role="dialog"][aria-label="Open a folder"]')?.textContent.includes('apps')`);
  await js(`document.querySelector('[role="dialog"][aria-label="Open a folder"] input[aria-label="Folder path"]').focus()`);
  await pressEnter(); await pressEnter(); await pressEnter();
  await wait(`window.folderFetchCount===4`);
  assert.ok(await js(`document.querySelector('[role="dialog"][aria-label="Open a folder"]')?.textContent.includes('apps')`), 'Repeated Enter keeps the current folder listing visible while navigation is pending');
  await js(`window.releaseFolderFetch.shift()();new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
  assert.ok(await js(`document.querySelector('[role="dialog"][aria-label="Open a folder"]')?.textContent.includes('apps')`), 'The first stale navigation response does not clear the listing');
  assert.equal(await js(`Array.from(document.querySelectorAll('[role="dialog"][aria-label="Open a folder"] button')).find(b=>b.textContent==='Open folder').disabled`), true, 'The newest folder request remains pending after the first stale response');
  await js(`window.releaseFolderFetch.shift()();new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
  assert.ok(await js(`document.querySelector('[role="dialog"][aria-label="Open a folder"]')?.textContent.includes('apps')`), 'The second stale navigation response does not clear the listing');
  assert.equal(await js(`Array.from(document.querySelectorAll('[role="dialog"][aria-label="Open a folder"] button')).find(b=>b.textContent==='Open folder').disabled`), true, 'The newest folder request remains pending after both stale responses');
  await js(`window.releaseFolderFetch.shift()()`);
  await wait(`!Array.from(document.querySelectorAll('[role="dialog"][aria-label="Open a folder"] button')).find(b=>b.textContent==='Open folder').disabled`);
  assert.ok(await js(`document.querySelector('[role="dialog"][aria-label="Open a folder"]')?.textContent.includes('apps')`), 'The folder listing remains visible after the newest request settles');
  // Unmount the picker before navigating: an in-flight listing + loadURL
  // left the renderer unable to run the next suite's scripts.
  await js(`document.querySelector('[role="dialog"][aria-label="Open a folder"] button[aria-label="Close"]').click()`);
  await wait(`!document.querySelector('[role="dialog"][aria-label="Open a folder"]')`);
  await wc.loadURL(origin);
  await wait(`!!document.querySelector('[data-workspace-ready="true"] textarea[aria-label="Prompt"]')`);
  win.setSize(900, 680);
  await js(`document.querySelector('button[aria-label="Projects"]').click()`);
  await wait(`!!document.querySelector('[aria-label="Search projects"]')`);
  assert.ok(await js(`(()=>{const r=document.querySelector('section[aria-label="Projects"]').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth})()`));
  await js(`Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Back to chat').click()`);
  await wait(`!!document.querySelector('[data-workspace-ready="true"] textarea[aria-label="Prompt"]')`);
  win.setSize(1100, 760);
  console.log('Projects passed: search, folder identity, scoped resume, exactly one new tab, visible Changes/Files, open folder.');
}
module.exports = { runProjectVisuals };
