const assert = require('node:assert/strict');
const testDesktop = require('./test-desktop.cjs');
const fs = require('node:fs');
const path = require('node:path');
async function runProjectVisuals({ win, origin, output }) {
  const wc = win.webContents, js = async code => {
    try { return await wc.executeJavaScript(code); }
    catch (error) { console.error('Project expression:', code); throw error; }
  };
  const pause = () => new Promise(resolve => setTimeout(resolve, 60));
  const wait = async code => { for (let i = 0; i < 100; i++) { if (await js(code)) return; await new Promise(r => setTimeout(r, 50)); } throw Error(`Project check timed out: ${code}`); };
  const key = async keyCode => {
    await testDesktop.testInput(wc, { type: 'keyDown', keyCode });
    await testDesktop.testInput(wc, { type: 'keyUp', keyCode });
    await pause();
  };
  await wait(`!!document.querySelector('[data-workspace-ready="true"] textarea[aria-label="Prompt"]')`);
  const settingsDialog = '[role="dialog"][aria-label^="Workspace settings"]';
  const openSettings = async () => {
    await wait(`!!document.querySelector('[data-workspace-trigger]')`);
    await js(`document.querySelector('[data-workspace-trigger]').click()`);
    await wait(`!!document.querySelector('[data-workspace-menu]')`);
    await wait(`!!Array.from(document.querySelectorAll('[data-workspace-menu] button')).find(b=>b.textContent.includes('Project settings'))`);
    await js(`Array.from(document.querySelectorAll('[data-workspace-menu] button')).find(b=>b.textContent.includes('Project settings')).click()`);
    await wait(`!!document.querySelector('${settingsDialog} [aria-label="Auto-approve tools"]')`);
  };
  await js(`window.projectRequests=[];const projectFetch=window.fetch;window.fetch=(input,options)=>{window.projectRequests.push(String(input));return projectFetch(input,options);};true`);
  await openSettings();
  const originalSettings = await js(`(()=>{const d=document.querySelector('${settingsDialog}');return {name:d.querySelector('input').value,yolo:d.querySelector('[aria-label="Auto-approve tools"]').getAttribute('aria-checked'),mcp:d.querySelector('[aria-label="Start MCP servers"]').getAttribute('aria-checked')}})()`);
  await js(`(()=>{const d=document.querySelector('${settingsDialog}'),e=d.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'cancel-probe');e.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('[aria-label="Auto-approve tools"]').click()})()`);
  assert.ok(await js(`!!document.querySelector('${settingsDialog}')`), 'Auto-approve switch keeps Project Settings open');
  assert.notEqual(await js(`document.querySelector('[aria-label="Auto-approve tools"]').getAttribute('aria-checked')`), originalSettings.yolo);
  await js(`Array.from(document.querySelectorAll('${settingsDialog} button')).find(b=>b.textContent==='Cancel').click()`);
  await wait(`!document.querySelector('${settingsDialog}')`);
  await openSettings();
  assert.deepEqual(await js(`(()=>{const d=document.querySelector('${settingsDialog}');return {name:d.querySelector('input').value,yolo:d.querySelector('[aria-label="Auto-approve tools"]').getAttribute('aria-checked')}})()`), { name: originalSettings.name, yolo: originalSettings.yolo }, 'Cancel discards the settings draft');
  await js(`(()=>{const d=document.querySelector('${settingsDialog}'),e=d.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'settings-save-probe');e.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('[aria-label="Auto-approve tools"]').click()})()`);
  assert.ok(await js(`!!document.querySelector('${settingsDialog}')`), 'Auto-approve switch still keeps the dialog open before Save');
  await js(`document.querySelector('[aria-label="Start MCP servers"]').click()`);
  assert.ok(await js(`!!document.querySelector('${settingsDialog}')`), 'MCP switch keeps Project Settings open');
  await js(`Array.from(document.querySelectorAll('${settingsDialog} button')).find(b=>b.textContent==='Save').click()`);
  await wait(`!document.querySelector('${settingsDialog}')`);
  await openSettings();
  assert.deepEqual(await js(`(()=>{const d=document.querySelector('${settingsDialog}');return {name:d.querySelector('input').value,yolo:d.querySelector('[aria-label="Auto-approve tools"]').getAttribute('aria-checked'),mcp:d.querySelector('[aria-label="Start MCP servers"]').getAttribute('aria-checked')}})()`), { name: 'settings-save-probe', yolo: originalSettings.yolo === 'true' ? 'false' : 'true', mcp: originalSettings.mcp === 'true' ? 'false' : 'true' }, 'Save persists the complete settings draft');
  await js(`(()=>{const d=document.querySelector('${settingsDialog}'),e=d.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(originalSettings.name)});e.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('[aria-label="Auto-approve tools"]').click()})()`);
  await js(`document.querySelector('[aria-label="Start MCP servers"]').click()`);
  await js(`Array.from(document.querySelectorAll('${settingsDialog} button')).find(b=>b.textContent==='Save').click()`);
  await wait(`!document.querySelector('${settingsDialog}')`);
  await js(`document.querySelector('button[aria-label="Projects"]').click()`);
  await wait(`!!document.querySelector('[aria-label="Search projects"]')`);
  await js(`(()=>{const e=document.querySelector('[aria-label="Search projects"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'folder-42');e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  await wait(`document.querySelectorAll('[data-project-path]').length===1`);
  assert.equal(await js(`document.querySelector('[data-project-path]').dataset.projectPath`), '/demo/folder-42');
  fs.writeFileSync(path.join(output, 'projects.png'), (await wc.capturePage()).toPNG());
  await js(`document.querySelector('[data-project-path] button').click()`);
  await wait(`document.querySelector('[data-conversation-project]')?.textContent==='/demo/folder-42'`);
  await wait(`window.projectRequests.some(p=>p.includes('/api/sessions?')&&p.includes('root=%2Fdemo%2Ffolder-42')&&p.includes('scope=local'))`);
  const before = await js(`document.querySelectorAll('[aria-label="Close tab"]').length`);
  await js(`document.querySelector('button[aria-label="Projects"]').click()`);
  await wait(`!!document.querySelector('[data-project-path="/demo/folder-42"]')`);
  await js(`document.querySelector('[data-project-path="/demo/folder-42"] button:last-child').click()`);
  await wait(`document.querySelector('[data-workspace-trigger] [title]')?.title.includes('/demo/folder-42')`);
  assert.equal(await js(`document.querySelectorAll('[aria-label="Close tab"]').length`), before + 1, 'New project chat creates exactly one tab');
  await js(`document.querySelector('button[aria-label="Projects"]').click()`);
  await wait(`!!document.querySelector('[data-project-path="/demo/folder-43"]')`);
  await js(`document.querySelector('[data-project-path="/demo/folder-43"] button:last-child').click()`);
  await wait(`document.querySelector('[data-workspace-trigger] [title]')?.title.includes('/demo/folder-43')`);
  await js(`document.querySelector('[aria-label="Close tab"]').parentElement.querySelector('button[aria-pressed]').click()`);
  await wait(`document.querySelector('[data-workspace-trigger] [title]')?.title.includes('/demo/folder-42')`);
  await js(`document.querySelector('button[aria-label="New chat"]').click()`);
  await wait(`document.querySelector('[data-workspace-trigger] [title]')?.title.includes('/demo/folder-42')`);
  await js(`document.querySelector('button[aria-label="Review workspace changes"]').click()`);
  await wait(`!!document.querySelector('[aria-label="Workspace changes"]')`);
  await wait(`document.body.textContent.includes('palette.css')`);
  await wait(`!!document.querySelector('button[aria-label="Files"]')`);
  await js(`document.querySelector('button[aria-label="Files"]').click()`);
  await wait(`!!document.querySelector('[aria-label="Workspace files"]')`);
  assert.equal(await js(`!!document.querySelector('[aria-label="Workspace changes"]')`), false);
  await js(`(()=>{window.folderPickerFetch=window.fetch;window.folderPickerRequests=[];window.fetch=(input,options)=>{const url=new URL(String(input),location.origin);if(url.pathname!='/api/workspaces'||options?.method)return window.folderPickerFetch(input,options);const requested=(url.searchParams.get('path')||'/demo/folder-42').replace(/\\/+$/,'');window.folderPickerRequests.push(requested);if(requested.endsWith('/mel'))return Promise.resolve(new Response(JSON.stringify({error:'not a directory'}),{status:404,headers:{'content-type':'application/json'}}));const entries=requested.includes('/melody-')?[]:Array.from({length:30},(_,i)=>{const name='melody-'+String(i).padStart(2,'0');return {name,path:requested+'/'+name,git:i===0,mtime:30-i};});return Promise.resolve(new Response(JSON.stringify({path:requested+'/',parent:'/demo',git:false,home:'/demo',default:'/demo/folder-42',entries}),{headers:{'content-type':'application/json'}}));};})()`);
  await js(`document.querySelector('button[aria-label="Open folder…"]').click()`);
  const folderDialog = '[role="dialog"][aria-label="Open a folder"]';
  const folderInput = `${folderDialog} input[aria-label="Folder path"]`;
  await wait(`document.querySelectorAll('${folderDialog} [role="option"]').length===30`);
  await js(`(()=>{const e=document.querySelector('${folderInput}'),base=e.value.replace(/\\/+$/,'');window.folderPickerPartial=base+'/mel';e.focus();Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,window.folderPickerPartial);e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  await wait(`document.querySelectorAll('${folderDialog} [role="option"]').length===30`);
  assert.equal(await js(`document.querySelector('${folderInput}').getAttribute('aria-activedescendant')`), null, 'typing does not choose a folder result');
  await key('Enter');
  await wait(`window.folderPickerRequests.includes(window.folderPickerPartial)`);
  assert.equal(await js(`document.querySelector('${folderInput}').value===window.folderPickerPartial&&document.querySelector('${folderInput}').getAttribute('aria-activedescendant')===null`), true, 'Enter without a selection submits only the typed path');
  await js(`document.querySelector('${folderInput}').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowUp',bubbles:true,cancelable:true}))`);
  const lastFolder = await js(`document.querySelector('${folderInput}').getAttribute('aria-activedescendant')`);
  assert.equal(lastFolder, await js(`Array.from(document.querySelectorAll('${folderDialog} [role="option"]')).at(-1).id`), 'ArrowUp starts at the last folder');
  await js(`document.querySelector('${folderInput}').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}))`);
  assert.equal(await js(`document.querySelector('${folderInput}').getAttribute('aria-activedescendant')`), lastFolder, 'ArrowDown clamps at the last folder');
  await js(`(()=>{const e=document.querySelector('${folderInput}'),base=window.folderPickerPartial.slice(0,-3);Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,base+'melo');e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  assert.equal(await js(`document.querySelector('${folderInput}').getAttribute('aria-activedescendant')`), null, 'editing the query resets the active result');
  await js(`(()=>{const e=document.querySelector('${folderInput}');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,window.folderPickerPartial);e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  for (let i = 0; i < 24; i++) {
    await js(`document.querySelector('${folderInput}').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}))`);
    await new Promise(resolve => setTimeout(resolve, 20));
  }
  const selectedFolder = await js(`document.querySelector('${folderInput}').getAttribute('aria-activedescendant')`);
  assert.ok(selectedFolder, 'ArrowDown activates a folder result');
  assert.ok(await js(`document.querySelector('${folderDialog} [role="listbox"]').parentElement.parentElement.scrollTop>0`), 'keyboard navigation keeps the active folder visible');
  const selectedPath = await js(`document.getElementById(${JSON.stringify(selectedFolder)}).title`);
  await key('Enter');
  await wait(`document.querySelector('${folderInput}').value===${JSON.stringify(selectedPath + '/')}`);
  assert.equal(await js(`document.activeElement===document.querySelector('${folderInput}')`), true, 'keyboard folder navigation keeps focus in the path field');
  await js(`window.fetch=window.folderPickerFetch;delete window.folderPickerFetch;delete window.folderPickerRequests;delete window.folderPickerPartial`);
  // Unmount the picker before navigating: an in-flight listing + loadURL
  // left the renderer unable to run the next suite's scripts.
  await js(`document.querySelector('${folderDialog} button[aria-label="Close"]').click()`);
  await wait(`!document.querySelector('[role="dialog"][aria-label="Open a folder"]')`);
  await wc.loadURL(origin);
  await wait(`!!document.querySelector('[data-workspace-ready="true"] textarea[aria-label="Prompt"]')`);
  win.setSize(900, 680);
  await js(`document.querySelector('button[aria-label="Projects"]').click()`);
  await wait(`!!document.querySelector('[aria-label="Search projects"]')`);
  assert.ok(await js(`(()=>{const r=document.querySelector('section[aria-label="Projects"]').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth})()`));
  await js(`Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Back to chat').click()`);
  await wait(`!!document.querySelector('[data-workspace-ready="true"] textarea[aria-label="Prompt"]')`);
  win.setSize(1100, 760);
  console.log('Projects passed: search, folder identity, scoped resume, exactly one new tab, visible Changes/Files, open folder.');
}
module.exports = { runProjectVisuals };
