// routes.zig — codegraff-gui backend route table (Phase 1 stubs).
//
// Each backend command is POST /api/<command> -> api/stub.render.
// Native OS operations (dialogs, clipboard, open path/URL) use window.mer.invoke,
// not HTTP. SSE /events is the raw_handler.
const mer = @import("mer");
const stub = @import("api/stub");

pub const routes: []const mer.Route = &.{
    .{ .path = "/api/open_workspace", .render = stub.render },
    .{ .path = "/api/get_runtime_status", .render = stub.render },
    .{ .path = "/api/get_session_snapshot", .render = stub.render },
    .{ .path = "/api/get_prompt_settings", .render = stub.render },
    .{ .path = "/api/get_theme_settings", .render = stub.render },
    .{ .path = "/api/update_theme_settings", .render = stub.render },
    .{ .path = "/api/list_providers", .render = stub.render },
    .{ .path = "/api/list_commands", .render = stub.render },
    .{ .path = "/api/select_conversation", .render = stub.render },
    .{ .path = "/api/ensure_conversation_view", .render = stub.render },
    .{ .path = "/api/start_new_chat", .render = stub.render },
    .{ .path = "/api/create_managed_chat", .render = stub.render },
    .{ .path = "/api/handoff_chat", .render = stub.render },
    .{ .path = "/api/send_prompt", .render = stub.render },
    .{ .path = "/api/stop_prompt", .render = stub.render },
    .{ .path = "/api/compact_conversation", .render = stub.render },
    .{ .path = "/api/run_slash_command", .render = stub.render },
    .{ .path = "/api/workspace_sync", .render = stub.render },
    .{ .path = "/api/workspace_query", .render = stub.render },
    .{ .path = "/api/build_workflow_draft", .render = stub.render },
    .{ .path = "/api/export_workflow_draft", .render = stub.render },
    .{ .path = "/api/set_active_agent", .render = stub.render },
    .{ .path = "/api/set_effort", .render = stub.render },
    .{ .path = "/api/set_fast", .render = stub.render },
    .{ .path = "/api/save_pasted_image", .render = stub.render },
    .{ .path = "/api/save_attachment_file", .render = stub.render },
    .{ .path = "/api/image_thumbnail", .render = stub.render },
    .{ .path = "/api/terminal_open", .render = stub.render },
    .{ .path = "/api/terminal_write", .render = stub.render },
    .{ .path = "/api/terminal_resize", .render = stub.render },
    .{ .path = "/api/terminal_close", .render = stub.render },
    .{ .path = "/api/list_mcp_servers", .render = stub.render },
    .{ .path = "/api/import_mcp_config", .render = stub.render },
    .{ .path = "/api/remove_mcp_server", .render = stub.render },
    .{ .path = "/api/reload_mcp_servers", .render = stub.render },
    .{ .path = "/api/login_mcp_server", .render = stub.render },
    .{ .path = "/api/logout_mcp_server", .render = stub.render },
    .{ .path = "/api/update_prompt_settings", .render = stub.render },
    .{ .path = "/api/start_provider_auth", .render = stub.render },
    .{ .path = "/api/complete_provider_auth", .render = stub.render },
    .{ .path = "/api/remove_provider", .render = stub.render },
    .{ .path = "/api/respond_followup", .render = stub.render },
    .{ .path = "/api/archive_conversation", .render = stub.render },
    .{ .path = "/api/archive_workspace", .render = stub.render },
    .{ .path = "/api/rename_workspace", .render = stub.render },
    .{ .path = "/api/clone_repository", .render = stub.render },
    .{ .path = "/api/quick_start_project", .render = stub.render },
    .{ .path = "/api/checkout_git_branch", .render = stub.render },
    .{ .path = "/api/create_git_branch", .render = stub.render },
    .{ .path = "/api/commit_git_changes", .render = stub.render },
    .{ .path = "/api/push_git_branch", .render = stub.render },
    .{ .path = "/api/read_workspace_file", .render = stub.render },
    .{ .path = "/api/save_conversation_layout", .render = stub.render },
    .{ .path = "/api/get_conversation_layout", .render = stub.render },
    .{ .path = "/api/create_saved_workspace", .render = stub.render },
    .{ .path = "/api/update_saved_workspace_layout", .render = stub.render },
    .{ .path = "/api/get_saved_workspace", .render = stub.render },
    .{ .path = "/api/rename_saved_workspace", .render = stub.render },
    .{ .path = "/api/delete_saved_workspace", .render = stub.render },
};
