// Public TypeScript types for @codegraff/sdk.
// The native bindings live in ./index.d.ts (auto-generated by napi-rs).

import { GraffApi, ChatStreamHandle, newConversationId, version } from "./index.js";

export { GraffApi, ChatStreamHandle, newConversationId, version };

// ── Options ──────────────────────────────────────────────────────────────

export interface RunAgentOptions {
  /** User prompt to send to the agent. */
  prompt: string;
  /** Working directory rooted to the codegraff workspace. Defaults to `process.cwd()`. */
  cwd?: string;
  /** Optional UUID of an existing conversation to resume. */
  conversationId?: string;
  /** Optional per-request model override. Must belong to the agent's authenticated provider. */
  model?: string;
}

export interface GraffSessionOptions {
  cwd?: string;
  conversationId?: string;
  model?: string;
}

export interface ChatOptions {
  prompt: string;
  conversationId?: string;
  model?: string;
}

export interface GraffInitOptions {
  /** Workspace root. Defaults to `process.cwd()`. */
  cwd?: string;
  /** Provider id (snake_case) — e.g. "openai", "anthropic", "open_router". */
  provider?: string;
  /** API key. Requires `provider`. The SDK calls `upsertCredential` after init. */
  apiKey?: string;
  /** Optional URL parameters for providers that need them (Vertex AI etc). */
  extraParams?: Array<[string, string]>;
  /** Pin the session model. Equivalent to `FORGE_SESSION__MODEL_ID`. */
  model?: string;
  /** Override the default 20480 max-tokens cap. Required for providers
   *  with smaller completion limits (gpt-4o-mini caps at 16384). */
  maxTokens?: number;
}

// ── Event stream ─────────────────────────────────────────────────────────

export type AgentEventCategory =
  | "action"
  | "info"
  | "debug"
  | "error"
  | "completion"
  | "warning";

export type AgentEventContent =
  | { kind: "ToolInput"; title: string; sub_title?: string | null; category: AgentEventCategory }
  | { kind: "ToolOutput"; text: string }
  | { kind: "Markdown"; text: string; partial: boolean };

export type AgentEventInterrupt =
  | { kind: "MaxToolFailurePerTurnLimitReached"; limit: number }
  | { kind: "MaxRequestPerTurnLimitReached"; limit: number };

export type AgentEvent =
  /** Synthetic event emitted by the SDK (not the Rust core) at the start of
   *  `runAgent` / `Graff.chat` / `GraffSession.send` so callers can capture
   *  the conversation id without inspecting the underlying handle. */
  | { type: "ConversationStarted"; conversationId: string }
  | { type: "TaskMessage"; content: AgentEventContent }
  | { type: "TaskReasoning"; content: string }
  | { type: "TaskComplete" }
  | { type: "ToolCallStart"; tool_call: ToolCallFull }
  | { type: "ToolCallEnd"; result: ToolResult }
  | { type: "RetryAttempt"; cause: string; duration_ms: number }
  | { type: "Interrupt"; reason: AgentEventInterrupt };

// ── Domain types (mirror forge_domain) ───────────────────────────────────
//
// These shapes are loose on purpose — the underlying Rust structs evolve
// quickly. The fields explicitly listed here are stable; the index signature
// allows access to less-stable fields without a TS error.

export interface Conversation {
  id: string;
  title?: string | null;
  metadata: { created_at: string; updated_at?: string | null };
  metrics: Record<string, unknown>;
  context?: Record<string, unknown> | null;
  [k: string]: unknown;
}

export interface AgentInfo {
  id: string;
  [k: string]: unknown;
}

export interface CompactionResult {
  /** Total tokens before compaction. */
  original_tokens?: number;
  /** Total tokens after compaction. */
  compacted_tokens?: number;
  [k: string]: unknown;
}

export interface ToolCallFull {
  name: string;
  call_id?: string | null;
  arguments: Record<string, unknown> | unknown;
  thought_signature?: string | null;
}

export interface ToolResult {
  name: string;
  call_id?: string | null;
  output: { is_error?: boolean; [k: string]: unknown };
}

export interface TrajectoryEvent {
  seq: number;
  agent_id: string;
  conversation_id: string;
  [k: string]: unknown;
}

// ── Top-level API ────────────────────────────────────────────────────────

export function runAgent(opts: RunAgentOptions): AsyncGenerator<AgentEvent, void, unknown>;

export class GraffSession {
  constructor(opts?: GraffSessionOptions);
  readonly conversationId: string | undefined;
  send(prompt: string): AsyncGenerator<AgentEvent, void, unknown>;
  close(): Promise<void>;
}

export class Graff {
  /** Initialise a long-lived Graff rooted at `cwd`. */
  /** Initialise a long-lived Graff. Pass a `cwd` string for legacy behavior,
   *  or an options object to also register a BYOK credential and pin the
   *  session provider/model in one call.
   *
   *  When neither `provider` nor `apiKey` is set, the SDK falls back to
   *  `~/.forge/forge.toml` (or the bundled defaults). Existing call sites
   *  passing just a string still work. */
  static init(arg?: string | GraffInitOptions): Promise<Graff>;

  /** Run a single chat turn. Same event stream as `runAgent` but reuses this Graff's GraffApi. */
  chat(opts: ChatOptions): AsyncGenerator<AgentEvent, void, unknown>;

  /** Create a multi-turn session that shares this Graff's underlying GraffApi. */
  session(opts?: GraffSessionOptions): GraffSession;

  // Auth (BYOK)
  upsertCredential(
    providerId: string,
    apiKey: string,
    extraParams?: Array<[string, string]> | null,
  ): Promise<void>;
  removeCredential(providerId: string): Promise<void>;

  // Conversation management
  listConversations(limit?: number): Promise<Conversation[]>;
  getConversation(id: string): Promise<Conversation | null>;
  lastConversation(): Promise<Conversation | null>;
  deleteConversation(id: string): Promise<void>;
  renameConversation(id: string, title: string): Promise<void>;
  compactConversation(id: string): Promise<CompactionResult>;

  // Agents
  getActiveAgent(): Promise<string | null>;
  setActiveAgent(agentId: string): Promise<void>;
  getAgentInfos(): Promise<AgentInfo[]>;

  // Observability
  listTrajectory(conversationId: string): Promise<TrajectoryEvent[]>;

  version(): string;
}
