#!/usr/bin/env python3
"""Generate the extension's theme CSS from the GUI stylesheets.

Single source of truth stays in gui/src/styles/:
  core.css              -> warm-graphite light + dark (:root / .dark)
  theme-presets.css     -> slate, nord, forest (light + dark)
  theme-foundations.css -> mono, rose (light + dark)

The popup must stand alone (no network, no bundler), so this bakes the
token blocks into apps/chrome-extension/theme.css plus a preset manifest
for popup.js. Re-run after any GUI theme change:

    python3 apps/chrome-extension/sync-theme.py

The extension only needs the color tokens the popup uses, but the file
carries the full token set so future extension pages re-theme for free.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CORE = ROOT / "gui/src/styles/core.css"
PRESETS = ROOT / "gui/src/styles/theme-presets.css"
FOUNDATIONS = ROOT / "gui/src/styles/theme-foundations.css"
OUT_CSS = Path(__file__).resolve().parent / "theme.css"
OUT_JSON = Path(__file__).resolve().parent / "theme-presets.json"

# Keep the full semantic token set: popup + any future extension page.
TOKENS = [
    "background", "foreground", "card", "card-foreground", "popover",
    "popover-foreground", "primary", "primary-foreground", "secondary",
    "secondary-foreground", "muted", "muted-foreground", "accent",
    "accent-foreground", "destructive", "border", "input", "ring",
    "accent-dim", "success", "warn", "faint",
]

SWATCH_TOKENS = {"bg": "background", "surface": "card", "accent": "accent", "text": "foreground"}


def block_vars(block: str) -> dict:
    found = {}
    for m in re.finditer(r"--([\w-]+)\s*:\s*([^;]+);", block):
        found[m.group(1)] = m.group(2).strip()
    return found


def extract(path: Path, light_sel: str, dark_sel: str) -> tuple:
    css = path.read_text()
    # core.css has several :root blocks (syntax tokens first); the theme
    # block is the one that defines --background, so match on content.
    light = dark = None
    for m in re.finditer(light_sel + r"\s*\{(.*?)\}", css, re.S):
        if "--background" in m.group(1):
            light = m
            break
    for m in re.finditer(dark_sel + r"\s*\{(.*?)\}", css, re.S):
        if "--background" in m.group(1):
            dark = m
            break
    if not light or not dark:
        raise SystemExit(f"selectors not found in {path}: {light_sel} / {dark_sel}")
    return block_vars(light.group(1)), block_vars(dark.group(1))


def main() -> None:
    presets: dict = {}
    # warm-graphite is the GUI default: :root / .dark in core.css.
    light, dark = extract(CORE, r":root", r"\.dark")
    presets["warm-graphite"] = (light, dark)
    for pid in ("slate", "nord", "forest"):
        light, dark = extract(
            PRESETS,
            rf':root\[data-theme="{pid}"\]',
            rf'\[data-theme="{pid}"\]\.dark',
        )
        presets[pid] = (light, dark)
    for pid in ("mono", "rose"):
        light, dark = extract(
            FOUNDATIONS,
            rf':root\[data-theme="{pid}"\]',
            rf'\[data-theme="{pid}"\]\.dark',
        )
        presets[pid] = (light, dark)

    missing = [
        f"{pid}/{mode}/{tok}"
        for pid, (li, da) in presets.items()
        for mode, vals in (("light", li), ("dark", da))
        for tok in TOKENS
        if tok not in vals
    ]
    if missing:
        raise SystemExit(f"tokens missing from GUI styles: {missing}")

    lines = [
        "/* GENERATED by sync-theme.py from gui/src/styles/. Do not hand-edit. */",
        "/* Same tokens as the desktop GUI: data-theme + .dark, light default. */",
        "",
    ]
    for pid, (li, da) in presets.items():
        sel = ':root[data-theme="{}"]'.format(pid) if pid != "warm-graphite" else ":root, :root[data-theme=\"warm-graphite\"]"
        lines.append(f"{sel} {{")
        lines += [f"  --{t}: {li[t]};" for t in TOKENS]
        lines.append("}")
        lines.append(f'{sel}.dark {{')
        lines += [f"  --{t}: {da[t]};" for t in TOKENS]
        lines.append("}")
        lines.append("")

    # Swatches mirror themePresets.ts dark previews (the picker chips).
    import json

    swatches = {
        pid: {k: da[v] for k, v in SWATCH_TOKENS.items()}
        for pid, (_, da) in presets.items()
        for li, da in [presets[pid]]
    }
    OUT_CSS.write_text("\n".join(lines))
    OUT_JSON.write_text(json.dumps({"presets": list(presets), "swatches": swatches}, indent=2) + "\n")
    print(f"wrote {OUT_CSS} + {OUT_JSON} ({len(presets)} presets)")


if __name__ == "__main__":
    sys.exit(main())
