"""AUTO-GENERATED by sdk/generate.py from `harness --schema`. Do not edit."""
from __future__ import annotations
import hashlib
import hmac
import json
import os
import re
import secrets
import subprocess
import threading
import time
import urllib.error
import urllib.request
from typing import Iterator, Optional

MODELS = ["MiniMax-M2.5", "MiniMax-M2.7", "MiniMax-M3", "claude-fable-5", "claude-haiku-4-5", "claude-opus-4-5", "claude-opus-4-6", "claude-opus-4-7", "claude-opus-4-8", "claude-opus-4.8", "claude-sonnet-4-5", "claude-sonnet-4-6", "claude-sonnet-4.6", "deepseek-chat", "deepseek-reasoner", "deepseek-v4-flash", "deepseek-v4-pro", "glm-4.5", "glm-4.7", "glm-5", "gpt-5-codex", "gpt-5.2", "gpt-5.4", "gpt-5.4-pro", "gpt-5.5", "gpt-5.5-codex", "grok-4.3", "grok-build", "kimi-k2.6", "kimi-k2.7", "mimo-v2-flash", "mimo-v2.5", "mimo-v2.5-pro", "mimo-v2.5-pro-ultraspeed", "minimax-m3"]
TOOLS = ["bash", "bash_output", "bash_kill", "read_file", "edit_file", "write_file", "webfetch", "codedb", "todo_write", "todo_read", "ask_user", "attempt_completion", "subagent", "workflow"]
PROVIDERS = ["anthropic", "codegraff", "deepseek", "openai", "minimax", "xiaomi", "kimi", "xai", "zai", "codex"]


def _sdk_install_id() -> str:
    """Anonymous per-install id for SDK telemetry — its own id file, distinct
    from the harness CLI's install id, so SDK users are counted separately.
    Only ever leaves the machine when the harness has an OTLP endpoint
    configured (OTEL_EXPORTER_OTLP_ENDPOINT); opt out entirely with
    GRAFF_NO_TELEMETRY=1 or by passing --no-telemetry in `args`."""
    path = os.path.join(os.path.expanduser("~"), ".simple-harness-sdk-id")
    try:
        with open(path) as f:
            v = f.read().strip()
        if len(v) == 32 and all(c in "0123456789abcdef" for c in v):
            return v
    except OSError:
        pass
    v = secrets.token_hex(16)
    try:
        with open(path, "w") as f:
            f.write(v + "\n")
    except OSError:
        pass
    return v


def _default_binary() -> str:
    """The CLI is `graff` (renamed from `harness`); prefer it when on PATH,
    fall back to the old name so pre-rename installs keep working."""
    import shutil
    return "graff" if shutil.which("graff") else "harness"


_TELEMETRY_DEFAULT = "https://harness-telemetry.rachpradhan.workers.dev"


def _report_error(kind: str, detail: str) -> None:
    """Best-effort OTLP ERROR log for failures the harness process cannot
    report itself (it may be dead or never have started): spawn failures,
    mid-turn exits, protocol breaks. Same pipeline and opt-out as harness
    telemetry — skipped when GRAFF_NO_TELEMETRY is set; endpoint from
    OTEL_EXPORTER_OTLP_ENDPOINT / GRAFF_OTEL_ENDPOINT, else the default
    collector. Fire-and-forget on a daemon thread; never raises."""
    if os.environ.get("GRAFF_NO_TELEMETRY"):
        return
    base = (os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT")
            or os.environ.get("GRAFF_OTEL_ENDPOINT")
            or _TELEMETRY_DEFAULT).rstrip("/")
    url = base if base.endswith("/v1/logs") else base + "/v1/logs"
    payload = json.dumps({"resourceLogs": [{
        "resource": {"attributes": [
            {"key": "service.name", "value": {"stringValue": "simple-harness"}},
            {"key": "client.name", "value": {"stringValue": os.environ.get("HARNESS_CLIENT", "sdk-py")}},
            {"key": "sdk.install.id", "value": {"stringValue": _sdk_install_id()}},
        ]},
        "scopeLogs": [{"scope": {"name": "simple-harness-sdk"}, "logRecords": [{
            "timeUnixNano": str(int(time.time() * 1e9)),
            "severityText": "ERROR",
            "body": {"stringValue": "error"},
            "attributes": [
                {"key": "kind", "value": {"stringValue": kind}},
                {"key": "detail", "value": {"stringValue": detail[:512]}},
            ],
        }]}],
    }]}).encode()

    def post():
        try:
            req = urllib.request.Request(
                url, data=payload, headers={
                    "Content-Type": "application/json",
                    # urllib's default Python-urllib/x.y UA is bot-blocked by
                    # Cloudflare in front of the collector (403) — identify.
                    "User-Agent": "simple-harness-sdk-py",
                })
            urllib.request.urlopen(req, timeout=3).read()
        except Exception:
            pass
    threading.Thread(target=post, daemon=True).start()


def _fleet_signal(kind: str, attrs: Optional[dict] = None) -> None:
    """Best-effort OTLP "fleet" log for the federated evolution loop (docs §9):
    propose / submit / elite_pull signals, tagged by client so CLI/TS/Python
    contributions stay distinguishable in /v1/stats. Same opt-out + endpoint as
    _report_error. Fire-and-forget on a daemon thread; never raises."""
    if os.environ.get("GRAFF_NO_TELEMETRY"):
        return
    base = (os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT")
            or os.environ.get("GRAFF_OTEL_ENDPOINT")
            or _TELEMETRY_DEFAULT).rstrip("/")
    url = base if base.endswith("/v1/logs") else base + "/v1/logs"
    al = [{"key": "kind", "value": {"stringValue": kind}}]
    for k, v in (attrs or {}).items():
        val = {"doubleValue": v} if isinstance(v, (int, float)) else {"stringValue": str(v)}
        al.append({"key": k, "value": val})
    payload = json.dumps({"resourceLogs": [{
        "resource": {"attributes": [
            {"key": "service.name", "value": {"stringValue": "simple-harness"}},
            {"key": "client.name", "value": {"stringValue": os.environ.get("HARNESS_CLIENT", "sdk-py")}},
            {"key": "sdk.install.id", "value": {"stringValue": _sdk_install_id()}},
        ]},
        "scopeLogs": [{"scope": {"name": "simple-harness-sdk"}, "logRecords": [{
            "timeUnixNano": str(int(time.time() * 1e9)),
            "body": {"stringValue": "fleet"},
            "attributes": al,
        }]}],
    }]}).encode()

    def post():
        try:
            req = urllib.request.Request(
                url, data=payload, headers={
                    "Content-Type": "application/json",
                    "User-Agent": "simple-harness-sdk-py",
                })
            urllib.request.urlopen(req, timeout=3).read()
        except Exception:
            pass
    threading.Thread(target=post, daemon=True).start()


def prompt_fingerprint(text: str) -> str:
    """Fingerprint of a system prompt as used in harness.trajectory.jsonl —
    the append-only DGM-style archive — and by `Harness.score()`:
    first 8 bytes of SHA-256, hex (16 chars)."""
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def score_signature(key: bytes, prompt_sha: str, parent_sha: str, score: float,
                    run_id: str, judge_id: str = "", artifact_sha: str = "",
                    eval_set_hash: str = "") -> str:
    """Recompute a score record's HMAC the way the harness signs it (Step 0,
    fitness-channel integrity). The canonical message is version-tagged and
    newline-joined with the score fixed to 6 decimals — byte-identical to the
    Zig signer (src/main.zig scoreSigMessage). `key` is the raw bytes of the
    GRAFF_SCORE_KEY_FILE file."""
    msg = "v1\n{}\n{}\n{:.6f}\n{}\n{}\n{}\n{}".format(
        prompt_sha, parent_sha, score, run_id, judge_id, artifact_sha, eval_set_hash)
    return hmac.new(key, msg.encode(), hashlib.sha256).hexdigest()


def verify_score(key: bytes, rec: dict) -> bool:
    """True iff a kind:"score" trajectory/D1 record carries a valid signature
    for `key`. Use this in an evolution driver's archive loader to reject
    forged fitness rows (an attacker without the key cannot produce a matching
    sig). Records with no sig fail closed when a key is set."""
    sig = rec.get("sig") or ""
    if not sig:
        return False
    want = score_signature(
        key, rec.get("prompt_sha", ""), rec.get("parent_sha", "") or "",
        float(rec.get("score", "nan")), rec.get("run_id", ""),
        rec.get("judge_id", ""), rec.get("artifact_sha", ""),
        rec.get("eval_set_hash", ""))
    return hmac.compare_digest(sig, want)

class Harness:
    """Drives a `harness --json` subprocess. One turn = send text, stream events.

    Events are plain dicts with a "type" field: "text", "tool_call",
    "ask_user", "tool_result", "turn", or "error" (see the harness
    --schema protocol).
    """

    def __init__(self, binary: Optional[str] = None, args: Optional[list] = None,
                 cwd: Optional[str] = None, env: Optional[dict] = None,
                 model: Optional[str] = None, yolo: bool = False,
                 system_prompt: Optional[str] = None,
                 append_system_prompt: Optional[str] = None):
        binary = binary or _default_binary()
        argv = [binary, "--json"]
        if yolo:
            argv.append("--yolo")
        if model:
            argv += ["--model", model]
        if system_prompt:
            argv += ["--system-prompt", system_prompt]
        if append_system_prompt:
            argv += ["--append-system-prompt", append_system_prompt]
        argv += list(args or [])
        # Tag the harness child as SDK-driven for telemetry attribution
        # (explicit caller values win). The id file is only read/created when
        # telemetry is actually live — same gating as the harness CLI's own id.
        run_env = dict(env if env is not None else os.environ)
        run_env.setdefault("HARNESS_CLIENT", "sdk-py")
        live = not run_env.get("GRAFF_NO_TELEMETRY") and (
            run_env.get("OTEL_EXPORTER_OTLP_ENDPOINT") or run_env.get("GRAFF_OTEL_ENDPOINT"))
        if live and "HARNESS_SDK_INSTALL_ID" not in run_env:
            run_env["HARNESS_SDK_INSTALL_ID"] = _sdk_install_id()
        try:
            self.proc = subprocess.Popen(
                argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                text=True, bufsize=1, cwd=cwd, env=run_env,
            )
        except OSError as e:
            _report_error("spawn", f"{binary}: {e}")
            raise

    def chat(self, text: str) -> Iterator[dict]:
        """Send a user turn; yield events until (and including) the 'turn'
        event. Raises RuntimeError (after reporting to telemetry) if the
        harness process dies mid-turn instead of silently yielding nothing."""
        assert self.proc.stdin and self.proc.stdout
        try:
            self.proc.stdin.write(json.dumps({"type": "user", "text": text}) + "\n")
            self.proc.stdin.flush()
        except OSError as e:
            _report_error("died", f"harness pipe closed on send: {e}")
            raise
        for line in self.proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue
            yield ev
            if ev.get("type") in ("turn", "error"):
                return
        # stdout EOF without a terminal event: the harness died mid-turn.
        rc = self.proc.poll()
        _report_error("died", f"harness exited mid-turn (rc={rc})")
        raise RuntimeError(f"harness exited mid-turn (rc={rc})")

    def ask(self, text: str) -> str:
        """Run a turn and return just the final assistant text."""
        final = ""
        for ev in self.chat(text):
            if ev.get("type") == "turn":
                final = ev["text"]
            elif ev.get("type") == "error":
                raise RuntimeError(ev["message"])
        return final

    def answer(self, text: str = "", cancelled: bool = False,
               call_id: Optional[str] = None) -> None:
        """Answer an in-flight ask_user event while chat() is being consumed."""
        assert self.proc.stdin
        req = {"type": "answer", "text": text, "cancelled": cancelled}
        if call_id:
            req["call_id"] = call_id
        self.proc.stdin.write(json.dumps(req) + "\n")
        self.proc.stdin.flush()

    def set_system_prompt(self, text: str, append: bool = False) -> None:
        """Replace (or with append=True, extend) the system prompt for later
        turns. Call between turns; blocks until the harness acks.

        KV-cache warning (Manus context-engineering lessons): the system
        prompt heads the cached prefix, so ANY mutation — append included —
        invalidates the cache for the whole conversation; the next turn
        re-reads everything at full input price. Prefer the spawn-time
        system_prompt/append_system_prompt arguments; mutate only at task
        boundaries, never back-and-forth inside a loop."""
        assert self.proc.stdin and self.proc.stdout
        self.proc.stdin.write(json.dumps(
            {"type": "set_system_prompt", "text": text, "append": append}) + "\n")
        self.proc.stdin.flush()
        for line in self.proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue
            if ev.get("type") == "error":
                raise RuntimeError(ev["message"])
            if ev.get("type") == "system_prompt":
                return
        _report_error("died", f"harness closed before acking set_system_prompt (rc={self.proc.poll()})")
        raise RuntimeError("harness closed before acking set_system_prompt")

    def append_system_prompt(self, text: str) -> None:
        """Tack extra instructions onto the current system prompt."""
        self.set_system_prompt(text, append=True)

    def score(self, prompt_or_sha: str, value: float, notes: str = "",
              parent: Optional[str] = None, judge_id: str = "",
              artifact_sha: str = "", eval_set_hash: str = "") -> None:
        """Record an evaluation score for an agent/prompt variant in the
        trajectory archive (harness.trajectory.jsonl) — the DGM evaluation
        phase writing back. `prompt_or_sha` is either the full system-prompt
        text (fingerprinted for you) or an existing 16-hex fingerprint.
        Pass `parent` (text or sha) when the variant was mutated from
        another prompt: that genome-lineage edge is what DGM parent
        selection counts children with.

        Provenance (signed when GRAFF_SCORE_KEY_FILE is set): `judge_id`
        names the evaluator, `artifact_sha` the thing it judged, and
        `eval_set_hash` the held-out eval used — all folded into the record's
        HMAC so a forged fitness row is detectable (see `verify_score`).
        Call between turns; blocks until the harness acks."""
        assert self.proc.stdin and self.proc.stdout
        sha = prompt_or_sha if re.fullmatch(r"[0-9a-f]{16}", prompt_or_sha) \
            else prompt_fingerprint(prompt_or_sha)
        req = {"type": "score", "prompt_sha": sha, "score": value, "notes": notes}
        if parent is not None:
            req["parent_sha"] = parent if re.fullmatch(r"[0-9a-f]{16}", parent) \
                else prompt_fingerprint(parent)
        if judge_id:
            req["judge_id"] = judge_id
        if artifact_sha:
            req["artifact_sha"] = artifact_sha
        if eval_set_hash:
            req["eval_set_hash"] = eval_set_hash
        self.proc.stdin.write(json.dumps(req) + "\n")
        self.proc.stdin.flush()
        for line in self.proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue
            if ev.get("type") == "error":
                raise RuntimeError(ev["message"])
            if ev.get("type") == "score":
                _fleet_signal("submit", {"prompt_sha": sha, "eval_set_hash": eval_set_hash})
                return
        _report_error("died", f"harness closed before acking score (rc={self.proc.poll()})")
        raise RuntimeError("harness closed before acking score")

    def pull_elites(self, provider_class: str, eval_set_hash: str = "") -> list:
        """Pull the fleet's live champion personas for a model tier (docs §9
        Step 2, GET /v1/elites). Emits a `fleet:elite_pull` signal and returns
        the elites list (empty when none are promoted yet). Hits the telemetry
        collector, not the harness subprocess."""
        base = (os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT")
                or os.environ.get("GRAFF_OTEL_ENDPOINT")
                or _TELEMETRY_DEFAULT).rstrip("/")
        if base.endswith("/v1/logs"):
            base = base[: -len("/v1/logs")]
        q = "provider_class=" + provider_class
        if eval_set_hash:
            q += "&eval_set_hash=" + eval_set_hash
        elites: list = []
        try:
            req = urllib.request.Request(
                base + "/v1/elites?" + q,
                headers={"User-Agent": "simple-harness-sdk-py"})
            body = urllib.request.urlopen(req, timeout=5).read()
            elites = (json.loads(body) or {}).get("elites", []) or []
        except Exception:
            pass
        _fleet_signal("elite_pull", {"provider_class": provider_class,
                                      "eval_set_hash": eval_set_hash,
                                      "n_elites": len(elites)})
        return elites
    def close(self):
        """Close stdin and give the harness a moment to exit cleanly — it
        flushes telemetry and trajectory records on the way out; killing it
        immediately would race (and lose) that flush."""
        if self.proc.stdin:
            self.proc.stdin.close()
        try:
            self.proc.wait(timeout=15)
        except subprocess.TimeoutExpired:
            self.proc.terminate()

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()


class RemoteHarness:
    """Drives a session on a remote `harness serve` bridge over HTTP — the
    network-transport analogue of `Harness`, same method surface. The server
    side runs `harness serve` (see the "serve" key of `harness --schema`);
    each session is a real `harness --json` child over there, and one POST =
    one protocol request, streamed back as NDJSON until its terminal event.

    Stdlib-only (urllib): usable anywhere Python runs, no local binary
    needed. Pass yolo=True in most cases — the bridge has no terminal to
    show permission prompts on."""

    def __init__(self, url: str, token: Optional[str] = None,
                 model: Optional[str] = None, yolo: bool = False,
                 system_prompt: Optional[str] = None,
                 append_system_prompt: Optional[str] = None,
                 session_id: Optional[str] = None):
        self.base = url.rstrip("/")
        self.token = token
        if session_id is not None:
            self.session_id = session_id
            return
        opts = {}
        if model:
            opts["model"] = model
        if yolo:
            opts["yolo"] = True
        if system_prompt:
            opts["system_prompt"] = system_prompt
        if append_system_prompt:
            opts["append_system_prompt"] = append_system_prompt
        resp = self._request("POST", "/v1/sessions", opts)
        self.session_id = json.loads(resp.read())["session_id"]

    def _request(self, method: str, path: str, body=None):
        headers = {"Content-Type": "application/json",
                   "User-Agent": "simple-harness-sdk-py"}
        if self.token:
            headers["Authorization"] = "Bearer " + self.token
        data = None if body is None else json.dumps(body).encode()
        req = urllib.request.Request(self.base + path, data=data,
                                     headers=headers, method=method)
        try:
            return urllib.request.urlopen(req)
        except urllib.error.HTTPError as e:
            detail = e.read().decode(errors="replace")[:256]
            raise RuntimeError(f"bridge {method} {path} → {e.code}: {detail}") from None

    def _send(self, payload: dict) -> Iterator[dict]:
        """POST one protocol request; yield its streamed NDJSON events."""
        resp = self._request("POST", f"/v1/sessions/{self.session_id}", payload)
        for line in resp:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue

    def chat(self, text: str) -> Iterator[dict]:
        """Send a user turn; yield events until (and including) the 'turn'
        event. Raises RuntimeError if the stream ends without one (the
        session process died server-side)."""
        terminal = False
        for ev in self._send({"type": "user", "text": text}):
            yield ev
            if ev.get("type") in ("turn", "error"):
                terminal = True
                return
        if not terminal:
            raise RuntimeError("bridge stream ended mid-turn (session process died?)")

    def ask(self, text: str) -> str:
        """Run a turn and return just the final assistant text."""
        final = ""
        for ev in self.chat(text):
            if ev.get("type") == "turn":
                final = ev["text"]
            elif ev.get("type") == "error":
                raise RuntimeError(ev["message"])
        return final

    def answer(self, text: str = "", cancelled: bool = False,
               call_id: Optional[str] = None) -> None:
        """Answer an in-flight ask_user event. The original chat stream
        continues and later yields the ask_user tool_result plus final turn."""
        req = {"type": "answer", "text": text, "cancelled": cancelled}
        if call_id:
            req["call_id"] = call_id
        self._request("POST", f"/v1/sessions/{self.session_id}", req).read()

    def set_system_prompt(self, text: str, append: bool = False) -> None:
        """Replace (or with append=True, extend) the system prompt for later
        turns. Same KV-cache warning as `Harness.set_system_prompt`: prefer
        the creation-time arguments; mutate only at task boundaries."""
        for ev in self._send({"type": "set_system_prompt", "text": text, "append": append}):
            if ev.get("type") == "error":
                raise RuntimeError(ev["message"])
            if ev.get("type") == "system_prompt":
                return
        raise RuntimeError("bridge stream ended before acking set_system_prompt")

    def append_system_prompt(self, text: str) -> None:
        """Tack extra instructions onto the current system prompt."""
        self.set_system_prompt(text, append=True)

    def score(self, prompt_or_sha: str, value: float, notes: str = "",
              parent: Optional[str] = None, judge_id: str = "",
              artifact_sha: str = "", eval_set_hash: str = "") -> None:
        """Record an evaluation score in the server-side trajectory archive —
        same semantics (and provenance fields) as `Harness.score`."""
        sha = prompt_or_sha if re.fullmatch(r"[0-9a-f]{16}", prompt_or_sha) \
            else prompt_fingerprint(prompt_or_sha)
        req = {"type": "score", "prompt_sha": sha, "score": value, "notes": notes}
        if parent is not None:
            req["parent_sha"] = parent if re.fullmatch(r"[0-9a-f]{16}", parent) \
                else prompt_fingerprint(parent)
        if judge_id:
            req["judge_id"] = judge_id
        if artifact_sha:
            req["artifact_sha"] = artifact_sha
        if eval_set_hash:
            req["eval_set_hash"] = eval_set_hash
        for ev in self._send(req):
            if ev.get("type") == "error":
                raise RuntimeError(ev["message"])
            if ev.get("type") == "score":
                return
        raise RuntimeError("bridge stream ended before acking score")

    def close(self):
        """Close the remote session (graceful: the bridge EOFs the child's
        stdin so it flushes telemetry/trajectory on the way out)."""
        try:
            self._request("DELETE", f"/v1/sessions/{self.session_id}").read()
        except (RuntimeError, OSError):
            pass

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()
