// AUTO-GENERATED by sdk/generate.py from `harness --schema`. Do not edit.

import { spawn, type ChildProcessByStdio } from "node:child_process";
import { createHash, randomBytes } from "node:crypto";
import { accessSync, constants, existsSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { homedir } from "node:os";
import { delimiter, dirname, join } from "node:path";
import { createInterface } from "node:readline";
import type { Readable, Writable } from "node:stream";

export const HARNESS_VERSION = "0.12";

export type ModelName = "MiniMax-M2.5" | "MiniMax-M2.7" | "MiniMax-M3" | "accounts/fireworks/models/deepseek-v4-flash" | "accounts/fireworks/models/deepseek-v4-pro" | "accounts/fireworks/models/glm-5p2" | "accounts/fireworks/models/gpt-oss-120b" | "accounts/fireworks/models/kimi-k2p6" | "accounts/fireworks/models/kimi-k2p7-code" | "accounts/fireworks/models/minimax-m3" | "accounts/fireworks/models/qwen3p7-plus" | "alibaba/qwen3.8-27b" | "anthropic/claude-sonnet-4.6" | "claude-fable-5" | "claude-haiku-4-5" | "claude-opus-4-5" | "claude-opus-4-6" | "claude-opus-4-7" | "claude-opus-4-8" | "claude-opus-4.8" | "claude-opus-5" | "claude-sonnet-4-5" | "claude-sonnet-4-6" | "claude-sonnet-4.6" | "claude-sonnet-5" | "deepseek-chat" | "deepseek-reasoner" | "deepseek-v4-flash" | "deepseek-v4-pro" | "fugu" | "fugu-ultra" | "fugu-ultra-20260615" | "gemma-4-31b" | "glm-4.5" | "glm-4.7" | "glm-5" | "glm-5-turbo" | "glm-5.2" | "glm-5.3" | "glm-5v-turbo" | "gpt-5-codex" | "gpt-5.2" | "gpt-5.3-codex-spark" | "gpt-5.4" | "gpt-5.4-mini" | "gpt-5.4-pro" | "gpt-5.5" | "gpt-5.6" | "gpt-5.6-luna" | "gpt-5.6-sol" | "gpt-5.6-terra" | "gpt-oss-120b" | "grok-4.3" | "grok-4.6" | "grok-build" | "k3" | "kilo-auto/small" | "kimi-for-coding" | "kimi-for-coding-highspeed" | "kimi-k2.6" | "kimi-latest" | "lmstudio" | "mimo-v2-flash" | "mimo-v2.5" | "mimo-v2.5-pro" | "mimo-v2.5-pro-ultraspeed" | "minimax-m3" | "mistral-medium-latest" | "mlx-community/Qwen3.6-27B-OptiQ-4bit" | "openai/gpt-oss-120b" | (string & {});
export type ToolName = "bash" | "bash_output" | "bash_kill" | "read_file" | "edit_file" | "write_file" | "webfetch" | "skill" | "codedb" | "read_tool_result" | "todo_write" | "todo_read" | "eval" | "note_constraint" | "ask_user" | "attempt_completion" | "load_tool_schemas" | "mcp_search_tools" | "mcp_select_tool" | "clock_sleep" | "subagent" | "workflow" | "agent_output" | "learn_candidate" | "peer_message" | "workspace" | "imagegen";
export type ProviderId = "anthropic" | "codegraff" | "deepseek" | "openai" | "minimax" | "xiaomi" | "kilo" | "groq" | "cerebras" | "mistral" | "kimi" | "moonshot" | "xai" | "zai" | "vercel" | "openrouter" | "fugu" | "fireworks" | "mlx" | "lmstudio" | "codex";

/** Events streamed by `harness --json` (one JSON object per stdout line), each
 *  discriminated by `type` — the analogue of codegraff's AgentEvent stream.
 *  `seq` is a monotonic, gap-free, 1-based per-session id: it is what lets a
 *  supervisor say exactly where it stopped reading, and it CONTINUES across a
 *  `--resume` rather than restarting (#330).
 *  Forward compatibility: a newer (edge) harness binary may stream event
 *  types not in this union; the runtime yields them as-is and every loop in
 *  this client only terminates on `turn`/`error`, so unknown events are safe
 *  to ignore in consumer code too. */
export type Event =
  | { seq: number; type: "text"; text: string }
  | { seq: number; type: "reasoning"; text: string }
  | { seq: number; type: "started"; provider: string; model: string }
  | { seq: number; type: "model_call_started"; provider: string; model: string }
  | { seq: number; type: "model_call_finished"; provider: string; model: string; ok: boolean; ms: number }
  | { seq: number; type: "tool_call"; name: string; input: Record<string, unknown> }
  | { seq: number; type: "tool_call_started"; name: string; input: Record<string, unknown> }
  | { seq: number; type: "tool_rejected"; name: string; reason: "budget" | "duplicate" | string; input: Record<string, unknown>; message: string }
  | { seq: number; type: "ask_user"; call_id: string; question: string; input: Record<string, unknown> }
  | { seq: number; type: "tool_result"; name: string; is_error: boolean; text: string }
  | { seq: number; type: "tool_call_finished"; name: string; is_error: boolean; ms: number }
  | { seq: number; type: "agent_usage"; id: string; ok: boolean; duration_ms: number; tool_calls: number; context_tokens: number; cache_read_tokens: number }
  | { seq: number; type: "finalizing" }
  | { seq: number; type: "session_recap"; text: string; status: "needs_input" | "completed" | "failed"; source: "heuristic" | "model" }
  | { seq: number; type: "turn"; text: string; context_tokens: number; cost_usd: number; input_tokens: number; uncached_input_tokens: number; cache_read_tokens: number; output_tokens: number; api_calls: number; subscription_calls: number; unpriced_calls: number; complete?: boolean; metadata_complete?: boolean }
  | { seq: number; type: "system_prompt"; ok: boolean; append: boolean; chars: number }
  | { seq: number; type: "model"; ok: boolean; provider: string; model: string; context: number; note: string }
  | { seq: number; type: "compact"; ok: boolean; chars: number }
  | { seq: number; type: "effort"; ok: boolean; level: string; applies: boolean }
  | { seq: number; type: "score"; ok: boolean; prompt_sha: string }
  | { seq: number; type: "error"; message: string };

/** Fingerprint of a system prompt as used in `.graff/trajectories` —
 *  the aggregate DGM-style archive — and by `Harness.score()`:
 *  first 8 bytes of SHA-256, hex (16 chars). */
export function promptFingerprint(text: string): string {
  return createHash("sha256").update(text).digest("hex").slice(0, 16);
}

// ── Options ──────────────────────────────────────────────────────────────

export interface HarnessOptions {
  /** Path to the CLI binary. Defaults to the matching optional
   *  `@codegraff/graff-*` package, then `graff` on PATH. */
  binary?: string;
  /** Working directory for the agent. Defaults to the parent process cwd. */
  cwd?: string;
  env?: NodeJS.ProcessEnv;
  /** Pin the startup model or provider, e.g. "gpt-5.5", "claude-opus-4-8", "codex". */
  model?: ModelName | ProviderId | string;
  /** Skip every bash/tool/MCP permission prompt (passes --yolo). */
  yolo?: boolean;
  /** Replace the built-in system prompt (the cwd project-instructions file is still appended). */
  systemPrompt?: string;
  /** Append extra text to the end of the system prompt. */
  appendSystemPrompt?: string;
  /** Hard per-turn root tool-call budget. */
  maxToolCalls?: number;
  /** Invocation-wide provider-call ceiling shared by all agent work. */
  maxModelCalls?: number;
  /** Reject duplicate root tool name+normalized-input calls per turn. */
  dedupeToolCalls?: boolean;
  /** Extra raw flags. `--json` is always added. */
  args?: string[];
}

/** Native image input for a user turn. URLs stay URLs on every provider;
 *  base64 is converted to that provider's image-content shape by Graff. */
export type ImageInput =
  | { type: "image_url"; url: string }
  | { type: "image_base64"; mediaType: string; data: string };

export interface ChatOptions {
  /** User prompt for this turn. */
  prompt: string;
  /** Native vision parts (max 16); never flattened into prompt text. */
  images?: ImageInput[];
  /** Run this turn in isolated, read-only review mode. */
  review?: boolean;
  /** Abort the turn mid-flight: on abort the SDK writes {"type":"cancel"}
   *  out-of-band (the REPL's Esc path); the stream still runs to the
   *  cancelled turn's terminal event — an `error` event ("turn cancelled"). */
  signal?: AbortSignal;
}

export interface AnswerOptions {
  text?: string;
  cancelled?: boolean;
  callId?: string;
}

/** Reasoning effort levels accepted by setEffort (protocol set_effort). */
export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max" | "ultra";

/** Structured result of one turn: the final assistant text plus the usage
 *  the harness reported on the terminal `turn` event. */
export interface AskResult {
  /** Final assistant text. */
  text: string;
  /** Server-reported context size at turn end. */
  contextTokens: number;
  /** Turn cost in USD. */
  costUsd: number;
  inputTokens: number;
  uncachedInputTokens: number;
  cacheReadTokens: number;
  outputTokens: number;
  /** Provider API calls made this turn. */
  apiCalls: number;
  /** Calls served under a subscription (unmetered) login. */
  subscriptionCalls: number;
  /** Calls with no pricing data. */
  unpricedCalls: number;
  /** False when the turn finished incomplete (interrupted/stalled). */
  complete?: boolean;
  metadataComplete?: boolean;
}

export interface RunAgentOptions extends HarnessOptions {
  /** User prompt to send to the agent. */
  prompt: string;
  /** Native vision parts (max 16); never flattened into prompt text. */
  images?: ImageInput[];
}

function spawnArgs(o: HarnessOptions): string[] {
  const a = ["--json"];
  if (o.yolo) a.push("--yolo");
  if (o.model) a.push("--model", o.model);
  if (o.maxToolCalls !== undefined) a.push("--max-tool-calls", String(o.maxToolCalls));
  if (o.maxModelCalls !== undefined) a.push("--max-model-calls", String(o.maxModelCalls));
  if (o.dedupeToolCalls) a.push("--dedupe-tool-calls");
  if (o.systemPrompt) a.push("--system-prompt", o.systemPrompt);
  if (o.appendSystemPrompt) a.push("--append-system-prompt", o.appendSystemPrompt);
  if (o.args) a.push(...o.args);
  return a;
}

/** Anonymous per-install id for SDK telemetry — its own id file, distinct
 *  from the harness CLI's install id, so SDK users aren't conflated with
 *  direct CLI users. Only ever leaves the machine when the harness has an
 *  OTLP endpoint configured (OTEL_EXPORTER_OTLP_ENDPOINT); opt out entirely
 *  with GRAFF_NO_TELEMETRY=1 or by passing --no-telemetry in `args`. */
function sdkInstallId(): string {
  const p = join(homedir(), ".simple-harness-sdk-id");
  try {
    const v = readFileSync(p, "utf8").trim();
    if (/^[0-9a-f]{32}$/.test(v)) return v;
  } catch {}
  const id = randomBytes(16).toString("hex");
  try { writeFileSync(p, id + "\n"); } catch {}
  return id;
}

const PLATFORM_PACKAGES: Readonly<Record<string, string>> = {
  "darwin-arm64": "@codegraff/graff-darwin-arm64",
  "darwin-x64": "@codegraff/graff-darwin-x64",
  "linux-arm64": "@codegraff/graff-linux-arm64",
  "linux-x64": "@codegraff/graff-linux-x64",
  "win32-arm64": "@codegraff/graff-win32-arm64",
  "win32-x64": "@codegraff/graff-win32-x64",
};

/** Resolve the binary bundled by npm. `createRequire` anchors lookup beside
 *  this installed SDK, so hoisted and nested optional dependencies both work. */
function packagedBinary(): { path?: string; packageName?: string } {
  const packageName = PLATFORM_PACKAGES[`${process.platform}-${process.arch}`];
  if (!packageName) return {};
  const require = createRequire(import.meta.url);
  let manifest: string;
  try { manifest = require.resolve(`${packageName}/package.json`); } catch {
    return { packageName };
  }
  let protocol: unknown;
  try { protocol = JSON.parse(readFileSync(manifest, "utf8")).graffProtocol; } catch {}
  if (protocol !== HARNESS_VERSION) {
    throw new Error(`${packageName} uses graff protocol ${String(protocol ?? "unknown")}, but @codegraff/sdk requires ${HARNESS_VERSION}. Reinstall @codegraff/sdk without disabling optional dependencies.`);
  }
  const binary = process.platform === "win32" ? "graff.exe" : "graff";
  const path = join(dirname(manifest), "bin", binary);
  return existsSync(path) ? { path, packageName } : { packageName };
}

/** Prefer the version-pinned npm binary, then a caller-supplied PATH. Return
 *  an absolute path so probing and spawning cannot disagree. */
function defaultBinary(env: NodeJS.ProcessEnv): string {
  const packaged = packagedBinary();
  if (packaged.path) return packaged.path;
  const binary = process.platform === "win32" ? "graff.exe" : "graff";
  for (const dir of (env.PATH ?? env.Path ?? env.path ?? "").split(delimiter)) {
    if (!dir) continue;
    const path = join(dir, binary);
    try {
      accessSync(path, process.platform === "win32" ? constants.F_OK : constants.X_OK);
      return path;
    } catch {}
  }
  const install = packaged.packageName
    ? `Reinstall @codegraff/sdk so npm can install ${packaged.packageName}, or install graff on PATH.`
    : "Install graff on PATH or pass Harness.init({ binary: ... }).";
  throw new Error(`No graff binary is available for ${process.platform}-${process.arch}. ${install}`);
}

const TELEMETRY_DEFAULT = "https://harness-telemetry.rachpradhan.workers.dev";

/** Best-effort OTLP ERROR log for failures the harness process cannot report
 *  itself (it may be dead or never have started): spawn failures, mid-turn
 *  exits. Same pipeline and opt-out as harness telemetry — skipped when
 *  GRAFF_NO_TELEMETRY is set; endpoint from OTEL_EXPORTER_OTLP_ENDPOINT /
 *  GRAFF_OTEL_ENDPOINT, else the default collector. Fire-and-forget. */
function reportError(kind: string, detail: string): void {
  if (process.env.GRAFF_NO_TELEMETRY) return;
  const base = (process.env.OTEL_EXPORTER_OTLP_ENDPOINT || process.env.GRAFF_OTEL_ENDPOINT || TELEMETRY_DEFAULT).replace(/\/+$/, "");
  const url = base.endsWith("/v1/logs") ? base : base + "/v1/logs";
  const payload = JSON.stringify({ resourceLogs: [{
    resource: { attributes: [
      { key: "service.name", value: { stringValue: "simple-harness" } },
      { key: "client.name", value: { stringValue: process.env.HARNESS_CLIENT ?? "sdk-ts" } },
      { key: "sdk.install.id", value: { stringValue: sdkInstallId() } },
    ] },
    scopeLogs: [{ scope: { name: "simple-harness-sdk" }, logRecords: [{
      timeUnixNano: String(Date.now() * 1e6),
      severityText: "ERROR",
      body: { stringValue: "error" },
      attributes: [
        { key: "kind", value: { stringValue: kind } },
        { key: "detail", value: { stringValue: detail.slice(0, 512) } },
      ],
    }] }],
  }] });
  try {
    fetch(url, {
      method: "POST",
      // default runtime UAs can be bot-blocked by Cloudflare in front of
      // the collector (403) — identify explicitly.
      headers: { "content-type": "application/json", "user-agent": "simple-harness-sdk-ts" },
      body: payload,
      signal: AbortSignal.timeout(3000),
    }).catch(() => {});
  } catch { /* fetch unavailable: drop */ }
}

/** Prompt-free SDK fleet signal. Local is the fail-closed default; SDKs have
 *  no interactive artifact-review UI, so prompt_text is never admitted. */
export function fleetSignal(kind: string, attrs: Record<string, string | number> = {}): void {
  if (process.env.GRAFF_NO_TELEMETRY) return;
  const privacy = process.env.GRAFF_LEARNING_PRIVACY ?? "local";
  if (!(["aggregate", "templates", "examples"] as string[]).includes(privacy)) return;
  const admitted = { ...attrs };
  delete admitted.prompt_text;
  let base = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || process.env.GRAFF_OTEL_ENDPOINT || TELEMETRY_DEFAULT;
  while (base.endsWith("/")) base = base.slice(0, -1);
  const url = base.endsWith("/v1/logs") ? base : base + "/v1/logs";
  const attributes: Array<Record<string, unknown>> = [
    { key: "kind", value: { stringValue: kind } },
  ];
  for (const [k, v] of Object.entries(admitted)) {
    attributes.push({ key: k, value: typeof v === "number" ? { doubleValue: v } : { stringValue: String(v) } });
  }
  const payload = JSON.stringify({ resourceLogs: [{
    resource: { attributes: [
      { key: "service.name", value: { stringValue: "simple-harness" } },
      { key: "client.name", value: { stringValue: process.env.HARNESS_CLIENT ?? "sdk-ts" } },
      { key: "sdk.install.id", value: { stringValue: sdkInstallId() } },
    ] },
    scopeLogs: [{ scope: { name: "simple-harness-sdk" }, logRecords: [{
      timeUnixNano: String(Date.now() * 1e6),
      body: { stringValue: "fleet" },
      attributes,
    }] }],
  }] });
  try {
    fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json", "user-agent": "simple-harness-sdk-ts" },
      body: payload,
      signal: AbortSignal.timeout(3000),
    }).catch(() => {});
  } catch { /* fetch unavailable: drop */ }
}

/** Spawn env: tag the harness child as SDK-driven for telemetry attribution
 *  (explicit caller values win). The id file is only read/created when
 *  telemetry is actually live — same gating as the harness CLI's own id. */
function sdkEnv(base?: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  const env = { ...(base ?? process.env) };
  env.HARNESS_CLIENT ??= "sdk-ts";
  const live = !env.GRAFF_NO_TELEMETRY &&
    (env.OTEL_EXPORTER_OTLP_ENDPOINT || env.GRAFF_OTEL_ENDPOINT);
  if (live && !env.HARNESS_SDK_INSTALL_ID) env.HARNESS_SDK_INSTALL_ID = sdkInstallId();
  return env;
}

// ── Harness (parallel to codegraff's `Graff`) ──────────────────────────────

/** A live `harness --json` agent. Multi-turn: each `chat()` / `session().send()`
 *  continues the same conversation (the process retains history). */
export class Harness {
  // stdin/stdout piped, stderr inherited (tool progress straight to the
  // user's terminal) — hence the ByStdio<Writable, Readable, null> shape.
  private proc: ChildProcessByStdio<Writable, Readable, null>;
  private queue: ((e: Event | null) => void)[] = [];
  private buffer: Event[] = [];
  /** Tail of the operation chain (see acquireOp). Always resolves. */
  private opTail: Promise<void> = Promise.resolve();
  private closed = false;
  private closePromise?: Promise<void>;

  constructor(opts: HarnessOptions = {}) {
    const env = sdkEnv(opts.env);
    this.proc = spawn(opts.binary ?? defaultBinary(env), spawnArgs(opts), {
      cwd: opts.cwd,
      env,
      stdio: ["pipe", "pipe", "inherit"],
    });
    const rl = createInterface({ input: this.proc.stdout });
    rl.on("line", (line) => {
      if (!line.trim()) return;
      let ev: Event;
      try { ev = JSON.parse(line) as Event; } catch { return; }
      const w = this.queue.shift();
      if (w) w(ev); else this.buffer.push(ev);
    });
    this.proc.on("close", () => { for (const w of this.queue) w(null); this.queue = []; });
    // Spawn failures (ENOENT etc.) never emit "close"; report and release
    // any waiters so callers get the mid-turn-death error instead of a hang.
    this.proc.on("error", (e) => {
      reportError("spawn", String(e));
      for (const w of this.queue) w(null);
      this.queue = [];
    });
    // cancel()/answer() are lock-free, so their writes can race process
    // death: swallow stdin stream errors instead of crashing the host.
    this.proc.stdin.on("error", () => {});
  }

  /** Start a long-lived agent (codegraff parity for `Graff.init`). */
  static init(opts: HarnessOptions = {}): Harness { return new Harness(opts); }

  private next(): Promise<Event | null> {
    if (this.buffer.length) return Promise.resolve(this.buffer.shift()!);
    return new Promise((resolve) => this.queue.push(resolve));
  }

  /** Operation chain: turns (chat) and acked controls (setSystemPrompt,
   *  setModel, setEffort, compact, score) run one at a time, so a control
   *  can never steal a chat's terminal event off the shared event queue.
   *  The tail always RESOLVES — an operation's error goes only to its own
   *  caller and can never poison the queue behind it. answer() and cancel()
   *  bypass the chain on purpose: the harness reads both out-of-band. */
  private acquireOp(): Promise<() => void> {
    if (this.closed) return Promise.reject(new Error("harness is closed"));
    let release!: () => void;
    const gate = new Promise<void>((resolve) => { release = resolve; });
    const acquired = this.opTail.then(() => release);
    this.opTail = this.opTail.then(() => gate);
    return acquired;
  }

  /** Run `op` holding the operation lock (see acquireOp). */
  private async runOp<T>(op: () => Promise<T>): Promise<T> {
    const release = await this.acquireOp();
    try {
      return await op();
    } finally {
      release();
    }
  }

  /** Run one turn; async-iterate events up to and including `turn`/`error`.
   *  Holds the operation lock until the terminal event, so a control issued
   *  mid-turn (setSystemPrompt, setModel, …) queues BEHIND the turn instead
   *  of stealing its events off the shared queue. Pass `signal` to cancel
   *  the turn (see ChatOptions.signal / cancel()). */
  async *chat(input: string | ChatOptions): AsyncGenerator<Event> {
    const prompt = typeof input === "string" ? input : input.prompt;
    const type = typeof input === "string" || !input.review ? "user" : "review";
    const images = typeof input === "string" ? undefined : input.images?.map((image) =>
      image.type === "image_base64"
        ? { type: image.type, media_type: image.mediaType, data: image.data }
        : image);
    const signal = typeof input === "string" ? undefined : input.signal;
    // Already aborted: send nothing — a cancel written before the turn's
    // first line would be cleared again when the turn starts.
    signal?.throwIfAborted();
    const release = await this.acquireOp();
    let aborted = false;
    const onAbort = () => { if (aborted) return; aborted = true; this.cancel(); };
    try {
      this.proc.stdin.write(JSON.stringify({ type, text: prompt, ...(images?.length ? { images } : {}) }) + "\n");
      if (signal) {
        signal.addEventListener("abort", onAbort, { once: true });
        if (signal.aborted) onAbort(); // aborted between the entry check and here
      }
      while (true) {
        const ev = await this.next();
        if (ev === null) {
          // Process closed without a terminal event: died mid-turn. Reported
          // to telemetry and thrown instead of silently ending the stream.
          reportError("died", `harness exited mid-turn (code=${this.proc.exitCode})`);
          throw new Error(`harness exited mid-turn (code=${this.proc.exitCode})`);
        }
        yield ev;
        if (ev.type === "turn" || ev.type === "error") return;
      }
    } finally {
      if (signal) signal.removeEventListener("abort", onAbort);
      release();
    }
  }

  /** Run a turn and return its final text plus the usage the harness
   *  reported on the terminal `turn` event (tokens, cost, call breakdown).
   *  Rejects on an `error` event — including a cancelled turn. */
  async askResult(input: string | ChatOptions): Promise<AskResult> {
    let result: AskResult | null = null;
    for await (const ev of this.chat(input)) {
      if (ev.type === "turn") {
        result = {
          text: ev.text,
          contextTokens: ev.context_tokens,
          costUsd: ev.cost_usd,
          inputTokens: ev.input_tokens,
          uncachedInputTokens: ev.uncached_input_tokens,
          cacheReadTokens: ev.cache_read_tokens,
          outputTokens: ev.output_tokens,
          apiCalls: ev.api_calls,
          subscriptionCalls: ev.subscription_calls,
          unpricedCalls: ev.unpriced_calls,
          complete: ev.complete,
          metadataComplete: ev.metadata_complete,
        };
      }
      if (ev.type === "error") throw new Error(ev.message);
    }
    if (!result) throw new Error("turn ended without a terminal event");
    return result;
  }

  /** Run a turn and return just the final assistant text. */
  async ask(input: string | ChatOptions): Promise<string> {
    return (await this.askResult(input)).text;
  }

  /** Run one isolated, read-only review turn and return its final report. */
  review(input: string | ChatOptions): Promise<string> {
    const options = typeof input === "string" ? { prompt: input } : input;
    return this.ask({ ...options, review: true });
  }

  /** Answer an in-flight ask_user event. Call this while consuming chat()
   *  when you receive { type: "ask_user", call_id, ... }. */
  answer(input: string | AnswerOptions): void {
    const payload = typeof input === "string"
      ? { type: "answer", text: input, cancelled: false }
      : { type: "answer", text: input.text ?? "", cancelled: input.cancelled ?? false, call_id: input.callId };
    this.proc.stdin.write(JSON.stringify(payload) + "\n");
  }

  /** Replace (or with append=true, extend) the system prompt for subsequent
   *  turns. Call between turns; resolves on the harness's ack.
   *
   *  KV-cache warning (Manus context-engineering lessons): the system prompt
   *  heads the cached prefix, so ANY mutation — append included — invalidates
   *  the cache for the whole conversation; the next turn re-reads everything
   *  at full input price. Prefer the spawn-time `systemPrompt` /
   *  `appendSystemPrompt` options; mutate only at task boundaries, never
   *  back-and-forth inside a loop. */
  async setSystemPrompt(text: string, append = false): Promise<void> {
    return this.runOp(async () => {
      this.proc.stdin.write(JSON.stringify({ type: "set_system_prompt", text, append }) + "\n");
      // Edge-version durability: a newer harness may emit event types this
      // client predates — skip them while waiting for the ack (the chat loop
      // already tolerates unknowns the same way) instead of throwing.
      while (true) {
        const ev = await this.next();
        if (ev === null) { reportError("died", "harness closed before acking set_system_prompt"); throw new Error("harness closed"); }
        if (ev.type === "error") throw new Error(ev.message);
        if (ev.type === "system_prompt") return;
      }
    });
  }

  /** Tack extra instructions onto the current system prompt. */
  appendSystemPrompt(text: string): Promise<void> { return this.setSystemPrompt(text, true); }

  /** Cancel the in-flight turn — the SDK analogue of the REPL's Esc. Writes
   *  {"type":"cancel"} straight to stdin, which the harness inbox reads
   *  OUT-OF-BAND (ahead of any queued request), so this deliberately does
   *  NOT join the operation queue: a cancel queued behind the turn it means
   *  to stop would fire too late. Lock-free like answer(). The active
   *  chat() stream still runs to the cancelled turn's terminal event. */
  cancel(): void {
    this.proc.stdin.write(JSON.stringify({ type: "cancel" }) + "\n");
  }

  /** Switch provider/model mid-session — the provider-qualified form of the
   *  protocol's set_model control. Call between turns; resolves on the
   *  `model` ack, rejects on the harness's `error` event (unknown model,
   *  missing key/login, …). Serialized with chat() and the other controls. */
  setModel(provider: ProviderId | string, model: ModelName | string): Promise<void> {
    return this.runOp(async () => {
      this.proc.stdin.write(JSON.stringify({ type: "set_model", provider, model }) + "\n");
      while (true) {
        const ev = await this.next();
        if (ev === null) { reportError("died", "harness closed before acking set_model"); throw new Error("harness closed"); }
        if (ev.type === "error") throw new Error(ev.message);
        if (ev.type === "model") return;
      }
    });
  }

  /** Set the reasoning effort for later turns (protocol set_effort).
   *  Resolves on the `effort` ack; serialized like the other controls. */
  setEffort(level: EffortLevel): Promise<void> {
    return this.runOp(async () => {
      this.proc.stdin.write(JSON.stringify({ type: "set_effort", level }) + "\n");
      while (true) {
        const ev = await this.next();
        if (ev === null) { reportError("died", "harness closed before acking set_effort"); throw new Error("harness closed"); }
        if (ev.type === "error") throw new Error(ev.message);
        if (ev.type === "effort") return;
      }
    });
  }

  /** Compact the conversation history now (protocol compact). Resolves on
   *  the `compact` ack; rejects when compaction fails — the harness leaves
   *  history unchanged in that case. Serialized like the other controls. */
  compact(): Promise<void> {
    return this.runOp(async () => {
      this.proc.stdin.write(JSON.stringify({ type: "compact" }) + "\n");
      while (true) {
        const ev = await this.next();
        if (ev === null) { reportError("died", "harness closed before acking compact"); throw new Error("harness closed"); }
        if (ev.type === "error") throw new Error(ev.message);
        if (ev.type === "compact") return;
      }
    });
  }

  /** Record an evaluation score for an agent/prompt variant in the
   *  aggregate `.graff/trajectories` archive — the DGM evaluation
   *  phase writing back. `promptOrSha` is either the full system-prompt
   *  text (fingerprinted for you) or an existing 16-hex fingerprint.
   *  Pass `parent` (text or sha) when the variant was mutated from another
   *  prompt: that genome-lineage edge is what DGM parent selection counts
   *  children with. Pass `niche` (reviewer/researcher/implementer/skeptic, or
   *  a custom agent) to file the score into that MAP-Elites cell so the fleet
   *  can promote a champion for the role; full text produces only a prompt-free
   *  fingerprint proposal until the SDK has review UI. Scale: the wire scale is
   *  [0, 1]. Pass scale "unit" to assert `value` is already in [0, 1]
   *  (anything else is rejected), or "percent" to always send value/100
   *  (accepts [0, 100] — a percent-scale 0.5 means 0.005, not 0.5). Without
   *  `scale` the harness heuristic applies: [0, 1] passes as-is, values in
   *  (1, 100] are treated as percentages and normalized to /100, and values
   *  outside [0, 100] are rejected. Call between turns; resolves on the
   *  harness's ack. */
  async score(promptOrSha: string, value: number, notes = "", parent?: string, niche?: string, scale?: "unit" | "percent"): Promise<void> {
    const sha = /^[0-9a-f]{16}$/.test(promptOrSha) ? promptOrSha : promptFingerprint(promptOrSha);
    const parent_sha = parent === undefined ? undefined
      : /^[0-9a-f]{16}$/.test(parent) ? parent : promptFingerprint(parent);
    // The SDK emitter strips prompt_text until it has an interactive review UI.
    if (niche && !/^[0-9a-f]{16}$/.test(promptOrSha)) fleetSignal("propose", { niche, prompt_sha: sha, parent_sha: parent_sha ?? "", prompt_text: promptOrSha });
    return this.runOp(async () => {
      this.proc.stdin.write(JSON.stringify({ type: "score", prompt_sha: sha, score: value, notes, parent_sha, niche, scale }) + "\n");
      // Same edge-version tolerance as setSystemPrompt: skip unknown events
      // while waiting for the ack.
      while (true) {
        const ev = await this.next();
        if (ev === null) { reportError("died", "harness closed before acking score"); throw new Error("harness closed"); }
        if (ev.type === "error") throw new Error(ev.message);
        if (ev.type === "score") { fleetSignal("submit", { prompt_sha: sha, parent_sha: parent_sha ?? "", niche: niche ?? "" }); return; }
      }
    });
  }

  /** Pull the fleet's live champion personas (GET /v1/elites). Local mode
   *  returns before contacting the telemetry collector. */
  async pullElites(providerClass: string, evalSetHash?: string): Promise<Array<Record<string, unknown>>> {
    if (!(["aggregate", "templates", "examples"] as string[]).includes(process.env.GRAFF_LEARNING_PRIVACY ?? "local")) return [];
    let base = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || process.env.GRAFF_OTEL_ENDPOINT || TELEMETRY_DEFAULT;
    while (base.endsWith("/")) base = base.slice(0, -1);
    if (base.endsWith("/v1/logs")) base = base.slice(0, -"/v1/logs".length);
    let q = "provider_class=" + encodeURIComponent(providerClass);
    if (evalSetHash) q += "&eval_set_hash=" + encodeURIComponent(evalSetHash);
    let elites: Array<Record<string, unknown>> = [];
    try {
      const res = await fetch(base + "/v1/elites?" + q, { signal: AbortSignal.timeout(5000) });
      const j = (await res.json()) as { elites?: Array<Record<string, unknown>> };
      elites = j?.elites ?? [];
    } catch { /* collector unreachable: no elites */ }
    fleetSignal("elite_pull", { provider_class: providerClass, eval_set_hash: evalSetHash ?? "", n_elites: elites.length });
    return elites;
  }

  /** A multi-turn session view over this agent (codegraff parity). */
  session(): HarnessSession { return new HarnessSession(this); }


  /** The harness schema version this client was generated from. */
  version(): string { return HARNESS_VERSION; }

  /** Cancel active work, close stdin, and await the child's clean exit so its
   *  telemetry and trajectory flushes are durable. Idempotent; force-kills
   *  only after the graceful deadline. */
  close(): Promise<void> {
    if (this.closePromise) return this.closePromise;
    this.cancel();
    this.closed = true;
    this.proc.stdin.end();
    this.closePromise = new Promise((resolve) => {
      if (this.proc.exitCode !== null) return resolve();
      const timer = setTimeout(() => this.proc.kill(), 15000);
      timer.unref?.();
      const finish = () => { clearTimeout(timer); resolve(); };
      this.proc.once("close", finish);
      this.proc.once("error", finish);
    });
    return this.closePromise;
  }

  /** Alias for close(). */
  dispose(): Promise<void> { return this.close(); }
}

// ── HarnessSession (parallel to codegraff's `GraffSession`) ────────────────

export class HarnessSession {
  private agent: Harness;
  /** Wrap an existing agent, or spawn a fresh one. */
  constructor(agent: Harness = new Harness()) { this.agent = agent; }
  /** Send a user turn; async-iterate its events. */
  send(input: string | ChatOptions): AsyncGenerator<Event> { return this.agent.chat(input); }
  ask(input: string | ChatOptions): Promise<string> { return this.agent.ask(input); }
  askResult(input: string | ChatOptions): Promise<AskResult> { return this.agent.askResult(input); }
  review(input: string | ChatOptions): Promise<string> { return this.agent.review(input); }
  answer(input: string | AnswerOptions): void { return this.agent.answer(input); }
  cancel(): void { this.agent.cancel(); }
  setSystemPrompt(text: string, append = false): Promise<void> { return this.agent.setSystemPrompt(text, append); }
  setModel(provider: ProviderId | string, model: ModelName | string): Promise<void> { return this.agent.setModel(provider, model); }
  setEffort(level: EffortLevel): Promise<void> { return this.agent.setEffort(level); }
  compact(): Promise<void> { return this.agent.compact(); }
  close(): Promise<void> { return this.agent.close(); }
  dispose(): Promise<void> { return this.agent.dispose(); }
}

// ── Top-level one-shot (parallel to codegraff's `runAgent`) ────────────────

/** Spawn an agent, run a single turn, stream its events, then close. */
export async function* runAgent(opts: RunAgentOptions): AsyncGenerator<Event> {
  const h = new Harness(opts);
  try {
    yield* h.chat({ prompt: opts.prompt, images: opts.images });
  } finally {
    await h.close();
  }
}

export const MODELS: ModelName[] = ["MiniMax-M2.5", "MiniMax-M2.7", "MiniMax-M3", "accounts/fireworks/models/deepseek-v4-flash", "accounts/fireworks/models/deepseek-v4-pro", "accounts/fireworks/models/glm-5p2", "accounts/fireworks/models/gpt-oss-120b", "accounts/fireworks/models/kimi-k2p6", "accounts/fireworks/models/kimi-k2p7-code", "accounts/fireworks/models/minimax-m3", "accounts/fireworks/models/qwen3p7-plus", "alibaba/qwen3.8-27b", "anthropic/claude-sonnet-4.6", "claude-fable-5", "claude-haiku-4-5", "claude-opus-4-5", "claude-opus-4-6", "claude-opus-4-7", "claude-opus-4-8", "claude-opus-4.8", "claude-opus-5", "claude-sonnet-4-5", "claude-sonnet-4-6", "claude-sonnet-4.6", "claude-sonnet-5", "deepseek-chat", "deepseek-reasoner", "deepseek-v4-flash", "deepseek-v4-pro", "fugu", "fugu-ultra", "fugu-ultra-20260615", "gemma-4-31b", "glm-4.5", "glm-4.7", "glm-5", "glm-5-turbo", "glm-5.2", "glm-5.3", "glm-5v-turbo", "gpt-5-codex", "gpt-5.2", "gpt-5.3-codex-spark", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-pro", "gpt-5.5", "gpt-5.6", "gpt-5.6-luna", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-oss-120b", "grok-4.3", "grok-4.6", "grok-build", "k3", "kilo-auto/small", "kimi-for-coding", "kimi-for-coding-highspeed", "kimi-k2.6", "kimi-latest", "lmstudio", "mimo-v2-flash", "mimo-v2.5", "mimo-v2.5-pro", "mimo-v2.5-pro-ultraspeed", "minimax-m3", "mistral-medium-latest", "mlx-community/Qwen3.6-27B-OptiQ-4bit", "openai/gpt-oss-120b"];
export const TOOLS: ToolName[] = ["bash", "bash_output", "bash_kill", "read_file", "edit_file", "write_file", "webfetch", "skill", "codedb", "read_tool_result", "todo_write", "todo_read", "eval", "note_constraint", "ask_user", "attempt_completion", "load_tool_schemas", "mcp_search_tools", "mcp_select_tool", "clock_sleep", "subagent", "workflow", "agent_output", "learn_candidate", "peer_message", "workspace", "imagegen"];
