// AUTO-GENERATED by sdk/generate.py from `harness --schema`. Do not edit.

import { spawn, type ChildProcessByStdio } from "node:child_process";
import { createHash, randomBytes } from "node:crypto";
import type { Readable, Writable } from "node:stream";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { createInterface } from "node:readline";

export const HARNESS_VERSION = "0.8";

export type ModelName = "MiniMax-M2.5" | "MiniMax-M2.7" | "MiniMax-M3" | "accounts/fireworks/models/deepseek-v4-flash" | "accounts/fireworks/models/deepseek-v4-pro" | "accounts/fireworks/models/glm-5p2" | "accounts/fireworks/models/gpt-oss-120b" | "accounts/fireworks/models/kimi-k2p6" | "accounts/fireworks/models/kimi-k2p7-code" | "accounts/fireworks/models/minimax-m3" | "accounts/fireworks/models/qwen3p7-plus" | "claude-fable-5" | "claude-haiku-4-5" | "claude-opus-4-5" | "claude-opus-4-6" | "claude-opus-4-7" | "claude-opus-4-8" | "claude-opus-4.8" | "claude-sonnet-4-5" | "claude-sonnet-4-6" | "claude-sonnet-4.6" | "deepseek-chat" | "deepseek-reasoner" | "deepseek-v4-flash" | "deepseek-v4-pro" | "fugu" | "fugu-ultra" | "fugu-ultra-20260615" | "glm-4.5" | "glm-4.7" | "glm-5" | "glm-5.2" | "gpt-5-codex" | "gpt-5.2" | "gpt-5.3-codex-spark" | "gpt-5.4" | "gpt-5.4-mini" | "gpt-5.4-pro" | "gpt-5.5" | "gpt-5.6" | "gpt-5.6-luna" | "gpt-5.6-sol" | "gpt-5.6-terra" | "grok-4.3" | "grok-build" | "k3" | "kimi-for-coding" | "kimi-for-coding-highspeed" | "kimi-k2.6" | "kimi-latest" | "lmstudio" | "mimo-v2-flash" | "mimo-v2.5" | "mimo-v2.5-pro" | "mimo-v2.5-pro-ultraspeed" | "minimax-m3" | "mlx-community/Qwen3.6-27B-OptiQ-4bit" | (string & {});
export type ToolName = "bash" | "bash_output" | "bash_kill" | "read_file" | "edit_file" | "write_file" | "webfetch" | "codedb" | "todo_write" | "todo_read" | "eval" | "ask_user" | "attempt_completion" | "clock_sleep" | "subagent" | "workflow" | "agent_output" | "learn_candidate";
export type ProviderId = "anthropic" | "codegraff" | "deepseek" | "openai" | "minimax" | "xiaomi" | "kimi" | "moonshot" | "xai" | "zai" | "fugu" | "fireworks" | "mlx" | "lmstudio" | "codex";

/** Events streamed by `harness --json` (one JSON object per stdout line), each
 *  discriminated by `type` — the analogue of codegraff's AgentEvent stream.
 *  Forward compatibility: a newer (edge) harness binary may stream event
 *  types not in this union; the runtime yields them as-is and every loop in
 *  this client only terminates on `turn`/`error`, so unknown events are safe
 *  to ignore in consumer code too. */
export type Event =
  | { type: "text"; text: string }
  | { type: "reasoning"; text: string }
  | { type: "started"; provider: string; model: string }
  | { type: "model_call_started"; provider: string; model: string }
  | { type: "model_call_finished"; provider: string; model: string; ok: boolean; ms: number }
  | { type: "tool_call"; name: string; input: Record<string, unknown> }
  | { type: "tool_call_started"; name: string; input: Record<string, unknown> }
  | { type: "tool_rejected"; name: string; reason: "budget" | "duplicate" | string; input: Record<string, unknown>; message: string }
  | { type: "ask_user"; call_id: string; question: string; input: Record<string, unknown> }
  | { type: "tool_result"; name: string; is_error: boolean; text: string }
  | { type: "tool_call_finished"; name: string; is_error: boolean; ms: number }
  | { type: "agent_usage"; id: string; ok: boolean; duration_ms: number; tool_calls: number; context_tokens: number; cache_read_tokens: number }
  | { type: "finalizing" }
  | { type: "turn"; text: string; context_tokens: number; cost_usd: number; complete?: boolean; metadata_complete?: boolean }
  | { type: "system_prompt"; ok: boolean; append: boolean; chars: number }
  | { type: "score"; ok: boolean; prompt_sha: string }
  | { type: "error"; message: string };

/** Fingerprint of a system prompt as used in `.graff/trajectories` —
 *  the aggregate DGM-style archive — and by `Harness.score()`:
 *  first 8 bytes of SHA-256, hex (16 chars). */
export function promptFingerprint(text: string): string {
  return createHash("sha256").update(text).digest("hex").slice(0, 16);
}

// ── Options ──────────────────────────────────────────────────────────────

export interface HarnessOptions {
  /** Path to the CLI binary (default: "graff" on PATH, falling back to its
   *  old name "harness"). */
  binary?: string;
  /** Working directory for the agent. Defaults to the parent process cwd. */
  cwd?: string;
  env?: NodeJS.ProcessEnv;
  /** Pin the startup model or provider, e.g. "gpt-5.5", "claude-opus-4-8", "codex". */
  model?: ModelName | ProviderId | string;
  /** Skip every bash/tool/MCP permission prompt (passes --yolo). */
  yolo?: boolean;
  /** Replace the built-in system prompt (the cwd project-instructions file is still appended). */
  systemPrompt?: string;
  /** Append extra text to the end of the system prompt. */
  appendSystemPrompt?: string;
  /** Hard per-turn root tool-call budget. */
  maxToolCalls?: number;
  /** Invocation-wide provider-call ceiling shared by all agent work. */
  maxModelCalls?: number;
  /** Reject duplicate root tool name+normalized-input calls per turn. */
  dedupeToolCalls?: boolean;
  /** Extra raw flags. `--json` is always added. */
  args?: string[];
}

export interface ChatOptions {
  /** User prompt for this turn. */
  prompt: string;
  /** Run this turn in isolated, read-only review mode. */
  review?: boolean;
}

export interface AnswerOptions {
  text?: string;
  cancelled?: boolean;
  callId?: string;
}

export interface RunAgentOptions extends HarnessOptions {
  /** User prompt to send to the agent. */
  prompt: string;
}

function spawnArgs(o: HarnessOptions): string[] {
  const a = ["--json"];
  if (o.yolo) a.push("--yolo");
  if (o.model) a.push("--model", o.model);
  if (o.maxToolCalls !== undefined) a.push("--max-tool-calls", String(o.maxToolCalls));
  if (o.maxModelCalls !== undefined) a.push("--max-model-calls", String(o.maxModelCalls));
  if (o.dedupeToolCalls) a.push("--dedupe-tool-calls");
  if (o.systemPrompt) a.push("--system-prompt", o.systemPrompt);
  if (o.appendSystemPrompt) a.push("--append-system-prompt", o.appendSystemPrompt);
  if (o.args) a.push(...o.args);
  return a;
}

/** Anonymous per-install id for SDK telemetry — its own id file, distinct
 *  from the harness CLI's install id, so SDK users aren't conflated with
 *  direct CLI users. Only ever leaves the machine when the harness has an
 *  OTLP endpoint configured (OTEL_EXPORTER_OTLP_ENDPOINT); opt out entirely
 *  with GRAFF_NO_TELEMETRY=1 or by passing --no-telemetry in `args`. */
function sdkInstallId(): string {
  const p = join(homedir(), ".simple-harness-sdk-id");
  try {
    const v = readFileSync(p, "utf8").trim();
    if (/^[0-9a-f]{32}$/.test(v)) return v;
  } catch {}
  const id = randomBytes(16).toString("hex");
  try { writeFileSync(p, id + "\n"); } catch {}
  return id;
}

/** The CLI is `graff` (renamed from `harness`); prefer it when on PATH,
 *  fall back to the old name so pre-rename installs keep working. */
function defaultBinary(): string {
  for (const dir of (process.env.PATH ?? "").split(":")) {
    if (dir && existsSync(join(dir, "graff"))) return "graff";
  }
  return "harness";
}

const TELEMETRY_DEFAULT = "https://harness-telemetry.rachpradhan.workers.dev";

/** Best-effort OTLP ERROR log for failures the harness process cannot report
 *  itself (it may be dead or never have started): spawn failures, mid-turn
 *  exits. Same pipeline and opt-out as harness telemetry — skipped when
 *  GRAFF_NO_TELEMETRY is set; endpoint from OTEL_EXPORTER_OTLP_ENDPOINT /
 *  GRAFF_OTEL_ENDPOINT, else the default collector. Fire-and-forget. */
function reportError(kind: string, detail: string): void {
  if (process.env.GRAFF_NO_TELEMETRY) return;
  const base = (process.env.OTEL_EXPORTER_OTLP_ENDPOINT || process.env.GRAFF_OTEL_ENDPOINT || TELEMETRY_DEFAULT).replace(/\/+$/, "");
  const url = base.endsWith("/v1/logs") ? base : base + "/v1/logs";
  const payload = JSON.stringify({ resourceLogs: [{
    resource: { attributes: [
      { key: "service.name", value: { stringValue: "simple-harness" } },
      { key: "client.name", value: { stringValue: process.env.HARNESS_CLIENT ?? "sdk-ts" } },
      { key: "sdk.install.id", value: { stringValue: sdkInstallId() } },
    ] },
    scopeLogs: [{ scope: { name: "simple-harness-sdk" }, logRecords: [{
      timeUnixNano: String(Date.now() * 1e6),
      severityText: "ERROR",
      body: { stringValue: "error" },
      attributes: [
        { key: "kind", value: { stringValue: kind } },
        { key: "detail", value: { stringValue: detail.slice(0, 512) } },
      ],
    }] }],
  }] });
  try {
    fetch(url, {
      method: "POST",
      // default runtime UAs can be bot-blocked by Cloudflare in front of
      // the collector (403) — identify explicitly.
      headers: { "content-type": "application/json", "user-agent": "simple-harness-sdk-ts" },
      body: payload,
      signal: AbortSignal.timeout(3000),
    }).catch(() => {});
  } catch { /* fetch unavailable: drop */ }
}

/** Prompt-free SDK fleet signal. Local is the fail-closed default; SDKs have
 *  no interactive artifact-review UI, so prompt_text is never admitted. */
export function fleetSignal(kind: string, attrs: Record<string, string | number> = {}): void {
  if (process.env.GRAFF_NO_TELEMETRY) return;
  const privacy = process.env.GRAFF_LEARNING_PRIVACY ?? "local";
  if (!(["aggregate", "templates", "examples"] as string[]).includes(privacy)) return;
  const admitted = { ...attrs };
  delete admitted.prompt_text;
  let base = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || process.env.GRAFF_OTEL_ENDPOINT || TELEMETRY_DEFAULT;
  while (base.endsWith("/")) base = base.slice(0, -1);
  const url = base.endsWith("/v1/logs") ? base : base + "/v1/logs";
  const attributes: Array<Record<string, unknown>> = [
    { key: "kind", value: { stringValue: kind } },
  ];
  for (const [k, v] of Object.entries(admitted)) {
    attributes.push({ key: k, value: typeof v === "number" ? { doubleValue: v } : { stringValue: String(v) } });
  }
  const payload = JSON.stringify({ resourceLogs: [{
    resource: { attributes: [
      { key: "service.name", value: { stringValue: "simple-harness" } },
      { key: "client.name", value: { stringValue: process.env.HARNESS_CLIENT ?? "sdk-ts" } },
      { key: "sdk.install.id", value: { stringValue: sdkInstallId() } },
    ] },
    scopeLogs: [{ scope: { name: "simple-harness-sdk" }, logRecords: [{
      timeUnixNano: String(Date.now() * 1e6),
      body: { stringValue: "fleet" },
      attributes,
    }] }],
  }] });
  try {
    fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json", "user-agent": "simple-harness-sdk-ts" },
      body: payload,
      signal: AbortSignal.timeout(3000),
    }).catch(() => {});
  } catch { /* fetch unavailable: drop */ }
}

/** Spawn env: tag the harness child as SDK-driven for telemetry attribution
 *  (explicit caller values win). The id file is only read/created when
 *  telemetry is actually live — same gating as the harness CLI's own id. */
function sdkEnv(base?: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  const env = { ...(base ?? process.env) };
  env.HARNESS_CLIENT ??= "sdk-ts";
  const live = !env.GRAFF_NO_TELEMETRY &&
    (env.OTEL_EXPORTER_OTLP_ENDPOINT || env.GRAFF_OTEL_ENDPOINT);
  if (live && !env.HARNESS_SDK_INSTALL_ID) env.HARNESS_SDK_INSTALL_ID = sdkInstallId();
  return env;
}

// ── Harness (parallel to codegraff's `Graff`) ──────────────────────────────

/** A live `harness --json` agent. Multi-turn: each `chat()` / `session().send()`
 *  continues the same conversation (the process retains history). */
export class Harness {
  // stdin/stdout piped, stderr inherited (tool progress straight to the
  // user's terminal) — hence the ByStdio<Writable, Readable, null> shape.
  private proc: ChildProcessByStdio<Writable, Readable, null>;
  private queue: ((e: Event | null) => void)[] = [];
  private buffer: Event[] = [];

  constructor(opts: HarnessOptions = {}) {
    this.proc = spawn(opts.binary ?? defaultBinary(), spawnArgs(opts), {
      cwd: opts.cwd,
      env: sdkEnv(opts.env),
      stdio: ["pipe", "pipe", "inherit"],
    });
    const rl = createInterface({ input: this.proc.stdout });
    rl.on("line", (line) => {
      if (!line.trim()) return;
      let ev: Event;
      try { ev = JSON.parse(line) as Event; } catch { return; }
      const w = this.queue.shift();
      if (w) w(ev); else this.buffer.push(ev);
    });
    this.proc.on("close", () => { for (const w of this.queue) w(null); this.queue = []; });
    // Spawn failures (ENOENT etc.) never emit "close"; report and release
    // any waiters so callers get the mid-turn-death error instead of a hang.
    this.proc.on("error", (e) => {
      reportError("spawn", String(e));
      for (const w of this.queue) w(null);
      this.queue = [];
    });
  }

  /** Start a long-lived agent (codegraff parity for `Graff.init`). */
  static init(opts: HarnessOptions = {}): Harness { return new Harness(opts); }

  private next(): Promise<Event | null> {
    if (this.buffer.length) return Promise.resolve(this.buffer.shift()!);
    return new Promise((resolve) => this.queue.push(resolve));
  }

  /** Run one turn; async-iterate events up to and including `turn`/`error`. */
  async *chat(input: string | ChatOptions): AsyncGenerator<Event> {
    const prompt = typeof input === "string" ? input : input.prompt;
    const type = typeof input === "string" || !input.review ? "user" : "review";
    this.proc.stdin.write(JSON.stringify({ type, text: prompt }) + "\n");
    while (true) {
      const ev = await this.next();
      if (ev === null) {
        // Process closed without a terminal event: died mid-turn. Reported
        // to telemetry and thrown instead of silently ending the stream.
        reportError("died", `harness exited mid-turn (code=${this.proc.exitCode})`);
        throw new Error(`harness exited mid-turn (code=${this.proc.exitCode})`);
      }
      yield ev;
      if (ev.type === "turn" || ev.type === "error") return;
    }
  }

  /** Run a turn and return just the final assistant text. */
  async ask(input: string | ChatOptions): Promise<string> {
    let final = "";
    for await (const ev of this.chat(input)) {
      if (ev.type === "turn") final = ev.text;
      if (ev.type === "error") throw new Error(ev.message);
    }
    return final;
  }

  /** Run one isolated, read-only review turn and return its final report. */
  review(input: string | ChatOptions): Promise<string> {
    const prompt = typeof input === "string" ? input : input.prompt;
    return this.ask({ prompt, review: true });
  }

  /** Answer an in-flight ask_user event. Call this while consuming chat()
   *  when you receive { type: "ask_user", call_id, ... }. */
  answer(input: string | AnswerOptions): void {
    const payload = typeof input === "string"
      ? { type: "answer", text: input, cancelled: false }
      : { type: "answer", text: input.text ?? "", cancelled: input.cancelled ?? false, call_id: input.callId };
    this.proc.stdin.write(JSON.stringify(payload) + "\n");
  }

  /** Replace (or with append=true, extend) the system prompt for subsequent
   *  turns. Call between turns; resolves on the harness's ack.
   *
   *  KV-cache warning (Manus context-engineering lessons): the system prompt
   *  heads the cached prefix, so ANY mutation — append included — invalidates
   *  the cache for the whole conversation; the next turn re-reads everything
   *  at full input price. Prefer the spawn-time `systemPrompt` /
   *  `appendSystemPrompt` options; mutate only at task boundaries, never
   *  back-and-forth inside a loop. */
  async setSystemPrompt(text: string, append = false): Promise<void> {
    this.proc.stdin.write(JSON.stringify({ type: "set_system_prompt", text, append }) + "\n");
    // Edge-version durability: a newer harness may emit event types this
    // client predates — skip them while waiting for the ack (the chat loop
    // already tolerates unknowns the same way) instead of throwing.
    while (true) {
      const ev = await this.next();
      if (ev === null) { reportError("died", "harness closed before acking set_system_prompt"); throw new Error("harness closed"); }
      if (ev.type === "error") throw new Error(ev.message);
      if (ev.type === "system_prompt") return;
    }
  }

  /** Tack extra instructions onto the current system prompt. */
  appendSystemPrompt(text: string): Promise<void> { return this.setSystemPrompt(text, true); }

  /** Record an evaluation score for an agent/prompt variant in the
   *  aggregate `.graff/trajectories` archive — the DGM evaluation
   *  phase writing back. `promptOrSha` is either the full system-prompt
   *  text (fingerprinted for you) or an existing 16-hex fingerprint.
   *  Pass `parent` (text or sha) when the variant was mutated from another
   *  prompt: that genome-lineage edge is what DGM parent selection counts
   *  children with. Pass `niche` (reviewer/researcher/implementer/skeptic, or
   *  a custom agent) to file the score into that MAP-Elites cell so the fleet
   *  can promote a champion for the role; full text produces only a prompt-free
   *  fingerprint proposal until the SDK has review UI. Scale: the wire scale is
   *  [0, 1]. Pass scale "unit" to assert `value` is already in [0, 1]
   *  (anything else is rejected), or "percent" to always send value/100
   *  (accepts [0, 100] — a percent-scale 0.5 means 0.005, not 0.5). Without
   *  `scale` the harness heuristic applies: [0, 1] passes as-is, values in
   *  (1, 100] are treated as percentages and normalized to /100, and values
   *  outside [0, 100] are rejected. Call between turns; resolves on the
   *  harness's ack. */
  async score(promptOrSha: string, value: number, notes = "", parent?: string, niche?: string, scale?: "unit" | "percent"): Promise<void> {
    const sha = /^[0-9a-f]{16}$/.test(promptOrSha) ? promptOrSha : promptFingerprint(promptOrSha);
    const parent_sha = parent === undefined ? undefined
      : /^[0-9a-f]{16}$/.test(parent) ? parent : promptFingerprint(parent);
    // The SDK emitter strips prompt_text until it has an interactive review UI.
    if (niche && !/^[0-9a-f]{16}$/.test(promptOrSha)) fleetSignal("propose", { niche, prompt_sha: sha, parent_sha: parent_sha ?? "", prompt_text: promptOrSha });
    this.proc.stdin.write(JSON.stringify({ type: "score", prompt_sha: sha, score: value, notes, parent_sha, niche, scale }) + "\n");
    // Same edge-version tolerance as setSystemPrompt: skip unknown events
    // while waiting for the ack.
    while (true) {
      const ev = await this.next();
      if (ev === null) { reportError("died", "harness closed before acking score"); throw new Error("harness closed"); }
      if (ev.type === "error") throw new Error(ev.message);
      if (ev.type === "score") { fleetSignal("submit", { prompt_sha: sha, parent_sha: parent_sha ?? "", niche: niche ?? "" }); return; }
    }
  }

  /** Pull the fleet's live champion personas (GET /v1/elites). Local mode
   *  returns before contacting the telemetry collector. */
  async pullElites(providerClass: string, evalSetHash?: string): Promise<Array<Record<string, unknown>>> {
    if (!(["aggregate", "templates", "examples"] as string[]).includes(process.env.GRAFF_LEARNING_PRIVACY ?? "local")) return [];
    let base = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || process.env.GRAFF_OTEL_ENDPOINT || TELEMETRY_DEFAULT;
    while (base.endsWith("/")) base = base.slice(0, -1);
    if (base.endsWith("/v1/logs")) base = base.slice(0, -"/v1/logs".length);
    let q = "provider_class=" + encodeURIComponent(providerClass);
    if (evalSetHash) q += "&eval_set_hash=" + encodeURIComponent(evalSetHash);
    let elites: Array<Record<string, unknown>> = [];
    try {
      const res = await fetch(base + "/v1/elites?" + q, { signal: AbortSignal.timeout(5000) });
      const j = (await res.json()) as { elites?: Array<Record<string, unknown>> };
      elites = j?.elites ?? [];
    } catch { /* collector unreachable: no elites */ }
    fleetSignal("elite_pull", { provider_class: providerClass, eval_set_hash: evalSetHash ?? "", n_elites: elites.length });
    return elites;
  }

  /** A multi-turn session view over this agent (codegraff parity). */
  session(): HarnessSession { return new HarnessSession(this); }


  /** The harness schema version this client was generated from. */
  version(): string { return HARNESS_VERSION; }

  /** Close stdin and give the harness a moment to exit cleanly — it flushes
   *  telemetry and trajectory records on the way out; killing immediately
   *  would race (and lose) that flush. */
  close(): void {
    this.proc.stdin.end();
    const t = setTimeout(() => this.proc.kill(), 15000);
    t.unref?.();
    this.proc.on("close", () => clearTimeout(t));
  }
}

// ── HarnessSession (parallel to codegraff's `GraffSession`) ────────────────

export class HarnessSession {
  private agent: Harness;
  /** Wrap an existing agent, or spawn a fresh one. */
  constructor(agent: Harness = new Harness()) { this.agent = agent; }
  /** Send a user turn; async-iterate its events. */
  send(input: string | ChatOptions): AsyncGenerator<Event> { return this.agent.chat(input); }
  ask(input: string | ChatOptions): Promise<string> { return this.agent.ask(input); }
  review(input: string | ChatOptions): Promise<string> { return this.agent.review(input); }
  answer(input: string | AnswerOptions): void { return this.agent.answer(input); }
  setSystemPrompt(text: string, append = false): Promise<void> { return this.agent.setSystemPrompt(text, append); }
  close(): void { this.agent.close(); }
}

// ── Top-level one-shot (parallel to codegraff's `runAgent`) ────────────────

/** Spawn an agent, run a single turn, stream its events, then close. */
export async function* runAgent(opts: RunAgentOptions): AsyncGenerator<Event> {
  const h = new Harness(opts);
  try {
    yield* h.chat({ prompt: opts.prompt });
  } finally {
    h.close();
  }
}

export const MODELS: ModelName[] = ["MiniMax-M2.5", "MiniMax-M2.7", "MiniMax-M3", "accounts/fireworks/models/deepseek-v4-flash", "accounts/fireworks/models/deepseek-v4-pro", "accounts/fireworks/models/glm-5p2", "accounts/fireworks/models/gpt-oss-120b", "accounts/fireworks/models/kimi-k2p6", "accounts/fireworks/models/kimi-k2p7-code", "accounts/fireworks/models/minimax-m3", "accounts/fireworks/models/qwen3p7-plus", "claude-fable-5", "claude-haiku-4-5", "claude-opus-4-5", "claude-opus-4-6", "claude-opus-4-7", "claude-opus-4-8", "claude-opus-4.8", "claude-sonnet-4-5", "claude-sonnet-4-6", "claude-sonnet-4.6", "deepseek-chat", "deepseek-reasoner", "deepseek-v4-flash", "deepseek-v4-pro", "fugu", "fugu-ultra", "fugu-ultra-20260615", "glm-4.5", "glm-4.7", "glm-5", "glm-5.2", "gpt-5-codex", "gpt-5.2", "gpt-5.3-codex-spark", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-pro", "gpt-5.5", "gpt-5.6", "gpt-5.6-luna", "gpt-5.6-sol", "gpt-5.6-terra", "grok-4.3", "grok-build", "k3", "kimi-for-coding", "kimi-for-coding-highspeed", "kimi-k2.6", "kimi-latest", "lmstudio", "mimo-v2-flash", "mimo-v2.5", "mimo-v2.5-pro", "mimo-v2.5-pro-ultraspeed", "minimax-m3", "mlx-community/Qwen3.6-27B-OptiQ-4bit"];
export const TOOLS: ToolName[] = ["bash", "bash_output", "bash_kill", "read_file", "edit_file", "write_file", "webfetch", "codedb", "todo_write", "todo_read", "eval", "ask_user", "attempt_completion", "clock_sleep", "subagent", "workflow", "agent_output", "learn_candidate"];
