// AUTO-GENERATED by sdk/generate.py from `harness --schema`. Do not edit.

// Edge-safe remote transport for a `harness serve` bridge: fetch + Web
// Streams only (no node: imports), so it runs on Cloudflare Workers, Deno,
// Bun, browsers, and Node >= 18. The server side is `harness serve`
// (see the "serve" key of `harness --schema`): each session is a real
// `harness --json` child over there, and one POST = one protocol request,
// streamed back as NDJSON until that request's terminal event.

export const HARNESS_VERSION = "0.10";

export type ModelName = "MiniMax-M2.5" | "MiniMax-M2.7" | "MiniMax-M3" | "accounts/fireworks/models/deepseek-v4-flash" | "accounts/fireworks/models/deepseek-v4-pro" | "accounts/fireworks/models/glm-5p2" | "accounts/fireworks/models/gpt-oss-120b" | "accounts/fireworks/models/kimi-k2p6" | "accounts/fireworks/models/kimi-k2p7-code" | "accounts/fireworks/models/minimax-m3" | "accounts/fireworks/models/qwen3p7-plus" | "claude-fable-5" | "claude-haiku-4-5" | "claude-opus-4-5" | "claude-opus-4-6" | "claude-opus-4-7" | "claude-opus-4-8" | "claude-opus-4.8" | "claude-sonnet-4-5" | "claude-sonnet-4-6" | "claude-sonnet-4.6" | "deepseek-chat" | "deepseek-reasoner" | "deepseek-v4-flash" | "deepseek-v4-pro" | "fugu" | "fugu-ultra" | "fugu-ultra-20260615" | "glm-4.5" | "glm-4.7" | "glm-5" | "glm-5.2" | "gpt-5-codex" | "gpt-5.2" | "gpt-5.3-codex-spark" | "gpt-5.4" | "gpt-5.4-mini" | "gpt-5.4-pro" | "gpt-5.5" | "gpt-5.6" | "gpt-5.6-luna" | "gpt-5.6-sol" | "gpt-5.6-terra" | "grok-4.3" | "grok-build" | "k3" | "kimi-for-coding" | "kimi-for-coding-highspeed" | "kimi-k2.6" | "kimi-latest" | "lmstudio" | "mimo-v2-flash" | "mimo-v2.5" | "mimo-v2.5-pro" | "mimo-v2.5-pro-ultraspeed" | "minimax-m3" | "mlx-community/Qwen3.6-27B-OptiQ-4bit" | (string & {});
export type ToolName = "bash" | "bash_output" | "bash_kill" | "read_file" | "edit_file" | "write_file" | "webfetch" | "skill" | "codedb" | "todo_write" | "todo_read" | "eval" | "ask_user" | "attempt_completion" | "clock_sleep" | "subagent" | "workflow" | "agent_output" | "learn_candidate";
export type ProviderId = "anthropic" | "codegraff" | "deepseek" | "openai" | "minimax" | "xiaomi" | "kimi" | "moonshot" | "xai" | "zai" | "fugu" | "fireworks" | "mlx" | "lmstudio" | "codex";

/** Events streamed by the bridge (same `--json` contract as the stdio SDK).
 *  `seq` is a monotonic, gap-free, 1-based per-session id the bridge forwards
 *  unchanged from the child and persists; reconnect with `?from=seq+1` to pick
 *  the stream back up exactly where you stopped (#330).
 *  Forward compatibility: a newer (edge) harness may stream event types not
 *  in this union; every loop here only terminates on its request's terminal
 *  event, so unknown events pass through and are safe to ignore. */
export type Event =
  | { seq: number; type: "text"; text: string }
  | { seq: number; type: "reasoning"; text: string }
  | { seq: number; type: "started"; provider: string; model: string }
  | { seq: number; type: "model_call_started"; provider: string; model: string }
  | { seq: number; type: "model_call_finished"; provider: string; model: string; ok: boolean; ms: number }
  | { seq: number; type: "tool_call"; name: string; input: Record<string, unknown> }
  | { seq: number; type: "tool_call_started"; name: string; input: Record<string, unknown> }
  | { seq: number; type: "tool_rejected"; name: string; reason: "budget" | "duplicate" | string; input: Record<string, unknown>; message: string }
  | { seq: number; type: "ask_user"; call_id: string; question: string; input: Record<string, unknown> }
  | { seq: number; type: "tool_result"; name: string; is_error: boolean; text: string }
  | { seq: number; type: "tool_call_finished"; name: string; is_error: boolean; ms: number }
  | { seq: number; type: "agent_usage"; id: string; ok: boolean; duration_ms: number; tool_calls: number; context_tokens: number; cache_read_tokens: number }
  | { seq: number; type: "finalizing" }
  | { seq: number; type: "turn"; text: string; context_tokens: number; cost_usd: number; complete?: boolean; metadata_complete?: boolean }
  | { seq: number; type: "system_prompt"; ok: boolean; append: boolean; chars: number }
  | { seq: number; type: "score"; ok: boolean; prompt_sha: string }
  | { seq: number; type: "error"; message: string };

/** Async (WebCrypto) variant of the trajectory-archive prompt fingerprint:
 *  first 8 bytes of SHA-256, hex (16 chars). */
export async function promptFingerprint(text: string): Promise<string> {
  const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(d).slice(0, 8)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

export interface RemoteOptions {
  /** Base URL of the `harness serve` bridge, e.g. "http://127.0.0.1:8787". */
  url: string;
  /** Bearer token (the bridge's --token / HARNESS_SERVE_TOKEN). */
  token?: string;
  /** Pin the session's model or provider (overrides the serve default). */
  model?: ModelName | ProviderId | string;
  /** Skip every permission prompt server-side (passes --yolo to the child).
   *  Usually what you want: the bridge has no terminal to ask on. */
  yolo?: boolean;
  /** Replace the built-in system prompt. */
  systemPrompt?: string;
  /** Append extra text to the system prompt. */
  appendSystemPrompt?: string;
  /** Hard per-turn root tool-call budget for the child session. */
  maxToolCalls?: number;
  /** Invocation-wide provider-call ceiling shared by all agent work. */
  maxModelCalls?: number;
  /** Reject duplicate root tool name+normalized-input calls per turn. */
  dedupeToolCalls?: boolean;
  /** Attach to an existing LIVE session on this bridge without creating one.
   *  Skips the create call entirely — use `session` to create-or-resume. */
  sessionId?: string;
  /** Name a DURABLE session (1-64 chars of [A-Za-z0-9._-]). The bridge runs
   *  the child as `graff --json --resume <session>` in its workspace, so the
   *  conversation is autosaved after every turn. Passing the same name to a
   *  REPLACEMENT bridge picks the run up from the last persisted turn, with
   *  the event sequence continuing rather than restarting (#330). Omitted:
   *  the bridge mints a fresh 16-hex name, which is still durable. */
  session?: string;
}

/** What the bridge reports when a session is created or resumed. */
export interface SessionInfo {
  /** The durable session id — also the graff session name on the server. */
  session_id: string;
  /** A session file already existed: this run continues an earlier one. */
  resumed: boolean;
  /** Highest seq on the persisted event tape. Reconnect from `last_seq + 1`. */
  last_seq: number;
}

export interface ChatOptions {
  prompt: string;
  review?: boolean;
  /** Replay persisted events with seq >= from before this turn's live ones. */
  from?: number;
}

export interface AnswerOptions {
  text?: string;
  cancelled?: boolean;
  callId?: string;
}

export interface RunAgentRemoteOptions extends RemoteOptions {
  prompt: string;
}

/** Parse a streaming NDJSON response body into events. */
async function* ndjson(res: Response): AsyncGenerator<Event> {
  const body = res.body;
  if (!body) throw new Error("bridge response had no body");
  const reader = body.getReader();
  const dec = new TextDecoder();
  let buf = "";
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buf += dec.decode(value, { stream: true });
    let i: number;
    while ((i = buf.indexOf("\n")) >= 0) {
      const line = buf.slice(0, i).trim();
      buf = buf.slice(i + 1);
      if (line) { try { yield JSON.parse(line) as Event; } catch { /* skip noise */ } }
    }
  }
  const tail = buf.trim();
  if (tail) { try { yield JSON.parse(tail) as Event; } catch { /* skip noise */ } }
}

const HEX16 = /^[0-9a-f]{16}$/;

/** A session on a remote `harness serve` bridge — the fetch-transport
 *  analogue of the stdio `Harness` class, same method surface.
 *
 *  Resumability (#330): every event carries a monotonic `seq`, tracked here as
 *  `lastSeq`. If a stream dies mid-turn, call `reconnect(h.lastSeq + 1)` — the
 *  bridge kept draining the child into a persisted log the whole time, so you
 *  get the events you missed and then the live tail. If the whole BRIDGE died,
 *  point a new `RemoteHarness` at the replacement with the same `session` name
 *  and the run continues from the last persisted turn. */
export class RemoteHarness {
  private base: string;
  private token?: string;
  /** Resolves to the session id (creation is lazy-started in the constructor). */
  readonly sessionId: Promise<string>;
  /** Resolves to the bridge's create/resume report; null when attaching by
   *  `sessionId` (no create call was made). */
  readonly info: Promise<SessionInfo | null>;
  /** Highest `seq` this client has seen. `reconnect(lastSeq + 1)` resumes
   *  exactly where it stopped; 0 before the first event. */
  lastSeq = 0;

  constructor(opts: RemoteOptions) {
    this.base = opts.url.replace(/\/+$/, "");
    this.token = opts.token;
    if (opts.sessionId) {
      this.sessionId = Promise.resolve(opts.sessionId);
      this.info = Promise.resolve(null);
    } else {
      const created = this.create(opts);
      this.info = created;
      this.sessionId = created.then((d) => d.session_id);
    }
  }

  /** Create a session (codegraff parity for `Graff.init`, remote edition). */
  static init(opts: RemoteOptions): RemoteHarness { return new RemoteHarness(opts); }

  private headers(): Record<string, string> {
    const h: Record<string, string> = { "content-type": "application/json" };
    if (this.token) h.authorization = `Bearer ${this.token}`;
    return h;
  }

  private async req(method: string, path: string, body?: unknown): Promise<Response> {
    const res = await fetch(this.base + path, {
      method,
      headers: this.headers(),
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      throw new Error(`bridge ${method} ${path} → ${res.status}: ${detail.slice(0, 256)}`);
    }
    return res;
  }

  private async create(opts: RemoteOptions): Promise<SessionInfo> {
    const body: Record<string, unknown> = {};
    if (opts.session) body.session = opts.session;
    if (opts.model) body.model = opts.model;
    if (opts.yolo !== undefined) body.yolo = opts.yolo;
    if (opts.systemPrompt) body.system_prompt = opts.systemPrompt;
    if (opts.appendSystemPrompt) body.append_system_prompt = opts.appendSystemPrompt;
    if (opts.maxToolCalls !== undefined) body.maxToolCalls = opts.maxToolCalls;
    if (opts.maxModelCalls !== undefined) body.maxModelCalls = opts.maxModelCalls;
    if (opts.dedupeToolCalls !== undefined) body.dedupeToolCalls = opts.dedupeToolCalls;
    const res = await this.req("POST", "/v1/sessions", body);
    const data = (await res.json()) as SessionInfo;
    this.lastSeq = data.last_seq ?? 0;
    return data;
  }

  /** Track the sequence as events go by, so a reconnect needs no bookkeeping
   *  from the caller. */
  private note(ev: Event): Event {
    if (typeof ev.seq === "number" && ev.seq > this.lastSeq) this.lastSeq = ev.seq;
    return ev;
  }

  /** Send one protocol request; stream its events. */
  private async *send(payload: Record<string, unknown>, from?: number): AsyncGenerator<Event> {
    const id = await this.sessionId;
    const q = from === undefined ? "" : `?from=${from}`;
    const res = await this.req("POST", `/v1/sessions/${id}${q}`, payload);
    for await (const ev of ndjson(res)) yield this.note(ev);
  }

  /** Run one turn; async-iterate events up to and including `turn`/`error`. */
  async *chat(input: string | ChatOptions): AsyncGenerator<Event> {
    const prompt = typeof input === "string" ? input : input.prompt;
    const type = typeof input === "string" || !input.review ? "user" : "review";
    const from = typeof input === "string" ? undefined : input.from;
    let terminal = false;
    for await (const ev of this.send({ type, text: prompt }, from)) {
      yield ev;
      if (ev.type === "turn" || ev.type === "error") { terminal = true; break; }
    }
    if (!terminal) throw new Error("bridge stream ended mid-turn (session process died?)");
  }

  /** Re-attach to a session after losing the stream: replay persisted events
   *  with `seq >= from` (default: everything after what this client already
   *  saw), then follow live until the in-flight request's terminal event.
   *  Sends nothing to the model, so it is safe to call while a turn is
   *  running — including from a different process than the one that started
   *  it. Also the way to read a completed turn you never received. */
  async *reconnect(from = this.lastSeq + 1): AsyncGenerator<Event> {
    const id = await this.sessionId;
    const res = await this.req("GET", `/v1/sessions/${id}/events?from=${from}`);
    for await (const ev of ndjson(res)) yield this.note(ev);
  }

  /** Run a turn and return just the final assistant text. */
  async ask(input: string | ChatOptions): Promise<string> {
    let final = "";
    for await (const ev of this.chat(input)) {
      if (ev.type === "turn") final = ev.text;
      if (ev.type === "error") throw new Error(ev.message);
    }
    return final;
  }

  /** Run one isolated, read-only review turn and return its final report. */
  review(input: string | ChatOptions): Promise<string> {
    const prompt = typeof input === "string" ? input : input.prompt;
    return this.ask({ prompt, review: true });
  }

  /** Answer an in-flight ask_user event. The original chat() stream continues
   *  and will later yield the ask_user tool_result plus the final turn. */
  async answer(input: string | AnswerOptions): Promise<void> {
    const payload = typeof input === "string"
      ? { type: "answer", text: input, cancelled: false }
      : { type: "answer", text: input.text ?? "", cancelled: input.cancelled ?? false, call_id: input.callId };
    const res = await this.req("POST", `/v1/sessions/${await this.sessionId}`, payload);
    await res.text();
  }


  /** Replace (or with append=true, extend) the system prompt for later turns.
   *  Same KV-cache warning as the stdio SDK: any mutation invalidates the
   *  cached prefix for the whole conversation — prefer the creation-time
   *  options; mutate only at task boundaries. */
  async setSystemPrompt(text: string, append = false): Promise<void> {
    for await (const ev of this.send({ type: "set_system_prompt", text, append })) {
      if (ev.type === "error") throw new Error(ev.message);
      if (ev.type === "system_prompt") return;
    }
    throw new Error("bridge stream ended before acking set_system_prompt");
  }

  appendSystemPrompt(text: string): Promise<void> { return this.setSystemPrompt(text, true); }

  /** Record an evaluation score in the server-side trajectory archive —
   *  same semantics as the stdio SDK's `score()`, including the optional
   *  `scale` ("unit" | "percent") override of the harness's
   *  value-normalization heuristic. */
  async score(promptOrSha: string, value: number, notes = "", parent?: string, niche?: string, scale?: "unit" | "percent"): Promise<void> {
    const sha = HEX16.test(promptOrSha) ? promptOrSha : await promptFingerprint(promptOrSha);
    const parent_sha = parent === undefined ? undefined
      : HEX16.test(parent) ? parent : await promptFingerprint(parent);
    // `niche` files the score into a MAP-Elites cell so the fleet can promote a
    // champion for the role; the remote harness reads it from the request and
    // tags its own score/submit. (Genome capture rides the harness process,
    // which holds the persona text the remote bridge only references by sha.)
    for await (const ev of this.send({ type: "score", prompt_sha: sha, score: value, notes, parent_sha, niche, scale })) {
      if (ev.type === "error") throw new Error(ev.message);
      if (ev.type === "score") return;
    }
    throw new Error("bridge stream ended before acking score");
  }

  /** The harness schema version this client was generated from. */
  version(): string { return HARNESS_VERSION; }

  /** Close the remote session (graceful: the bridge EOFs the child's stdin
   *  so it flushes telemetry/trajectory on the way out). */
  async close(): Promise<void> {
    const id = await this.sessionId;
    await this.req("DELETE", `/v1/sessions/${id}`).catch(() => {});
  }
}

/** Create a remote session, run a single turn, stream its events, close. */
export async function* runAgentRemote(opts: RunAgentRemoteOptions): AsyncGenerator<Event> {
  const h = new RemoteHarness(opts);
  try {
    yield* h.chat({ prompt: opts.prompt });
  } finally {
    await h.close();
  }
}

export const MODELS: ModelName[] = ["MiniMax-M2.5", "MiniMax-M2.7", "MiniMax-M3", "accounts/fireworks/models/deepseek-v4-flash", "accounts/fireworks/models/deepseek-v4-pro", "accounts/fireworks/models/glm-5p2", "accounts/fireworks/models/gpt-oss-120b", "accounts/fireworks/models/kimi-k2p6", "accounts/fireworks/models/kimi-k2p7-code", "accounts/fireworks/models/minimax-m3", "accounts/fireworks/models/qwen3p7-plus", "claude-fable-5", "claude-haiku-4-5", "claude-opus-4-5", "claude-opus-4-6", "claude-opus-4-7", "claude-opus-4-8", "claude-opus-4.8", "claude-sonnet-4-5", "claude-sonnet-4-6", "claude-sonnet-4.6", "deepseek-chat", "deepseek-reasoner", "deepseek-v4-flash", "deepseek-v4-pro", "fugu", "fugu-ultra", "fugu-ultra-20260615", "glm-4.5", "glm-4.7", "glm-5", "glm-5.2", "gpt-5-codex", "gpt-5.2", "gpt-5.3-codex-spark", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-pro", "gpt-5.5", "gpt-5.6", "gpt-5.6-luna", "gpt-5.6-sol", "gpt-5.6-terra", "grok-4.3", "grok-build", "k3", "kimi-for-coding", "kimi-for-coding-highspeed", "kimi-k2.6", "kimi-latest", "lmstudio", "mimo-v2-flash", "mimo-v2.5", "mimo-v2.5-pro", "mimo-v2.5-pro-ultraspeed", "minimax-m3", "mlx-community/Qwen3.6-27B-OptiQ-4bit"];
export const TOOLS: ToolName[] = ["bash", "bash_output", "bash_kill", "read_file", "edit_file", "write_file", "webfetch", "skill", "codedb", "todo_write", "todo_read", "eval", "ask_user", "attempt_completion", "clock_sleep", "subagent", "workflow", "agent_output", "learn_candidate"];
