#!/usr/bin/env python3
"""Generate the TypeScript and Python SDKs from `harness --schema`.

Single source of truth: the harness emits its own interface (providers,
models, tools, and the --json event protocol). This script turns that JSON
into typed clients in sdk/ts/ and sdk/py/. Run in CI on every release so the
SDKs never drift from the binary — never hand-edit the generated files.

Usage:
    harness --schema | python3 sdk/generate.py
    python3 sdk/generate.py --schema path/to/schema.json
    python3 sdk/generate.py --harness ./zig-out/bin/harness   # runs it for you
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def load_schema(argv):
    if "--schema" in argv:
        with open(argv[argv.index("--schema") + 1]) as f:
            return json.load(f)
    if "--harness" in argv:
        binary = argv[argv.index("--harness") + 1]
        out = subprocess.run([binary, "--schema"], capture_output=True, text=True, check=True)
        return json.loads(out.stdout)
    if sys.stdin.isatty():
        sys.exit("no schema: pipe `harness --schema` in, or pass --schema FILE / --harness BIN")
    return json.load(sys.stdin)


def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {os.path.relpath(path, HERE)} ({len(content)} bytes)")


def gen_ts(schema):
    models = sorted({m["name"] for m in schema["models"]})
    tools = [t["name"] for t in schema["tools"]]
    providers = [p["id"] for p in schema["providers"]]
    version = schema.get("version", "0")
    model_union = " | ".join(f'"{m}"' for m in models)
    tool_union = " | ".join(f'"{t}"' for t in tools)
    provider_union = " | ".join(f'"{p}"' for p in providers)
    header = "// AUTO-GENERATED by sdk/generate.py from `harness --schema`. Do not edit.\n"
    return header + f'''
import {{ spawn, type ChildProcessByStdio }} from "node:child_process";
import {{ createHash, randomBytes }} from "node:crypto";
import type {{ Readable, Writable }} from "node:stream";
import {{ existsSync, readFileSync, writeFileSync }} from "node:fs";
import {{ homedir }} from "node:os";
import {{ join }} from "node:path";
import {{ createInterface }} from "node:readline";

export const HARNESS_VERSION = "{version}";

export type ModelName = {model_union};
export type ToolName = {tool_union};
export type ProviderId = {provider_union};

/** Events streamed by `harness --json` (one JSON object per stdout line), each
 *  discriminated by `type` — the analogue of codegraff's AgentEvent stream.
 *  Forward compatibility: a newer (edge) harness binary may stream event
 *  types not in this union; the runtime yields them as-is and every loop in
 *  this client only terminates on `turn`/`error`, so unknown events are safe
 *  to ignore in consumer code too. */
export type Event =
  | {{ type: "text"; text: string }}
  | {{ type: "tool_call"; name: string; input: Record<string, unknown> }}
  | {{ type: "tool_result"; name: string; is_error: boolean; text: string }}
  | {{ type: "turn"; text: string; context_tokens: number; cost_usd: number }}
  | {{ type: "system_prompt"; ok: boolean; append: boolean; chars: number }}
  | {{ type: "score"; ok: boolean; prompt_sha: string }}
  | {{ type: "error"; message: string }};

/** Fingerprint of a system prompt as used in harness.trajectory.jsonl —
 *  the append-only DGM-style archive — and by `Harness.score()`:
 *  first 8 bytes of SHA-256, hex (16 chars). */
export function promptFingerprint(text: string): string {{
  return createHash("sha256").update(text).digest("hex").slice(0, 16);
}}

// ── Options ──────────────────────────────────────────────────────────────

export interface HarnessOptions {{
  /** Path to the CLI binary (default: "graff" on PATH, falling back to its
   *  old name "harness"). */
  binary?: string;
  /** Working directory for the agent. Defaults to the parent process cwd. */
  cwd?: string;
  env?: NodeJS.ProcessEnv;
  /** Pin the startup model or provider, e.g. "gpt-5.5", "claude-opus-4-8", "codex". */
  model?: ModelName | ProviderId | string;
  /** Skip every bash/tool/MCP permission prompt (passes --yolo). */
  yolo?: boolean;
  /** Replace the built-in system prompt (the cwd project-instructions file is still appended). */
  systemPrompt?: string;
  /** Append extra text to the end of the system prompt. */
  appendSystemPrompt?: string;
  /** Extra raw flags. `--json` is always added. */
  args?: string[];
}}

export interface ChatOptions {{
  /** User prompt for this turn. */
  prompt: string;
}}

export interface RunAgentOptions extends HarnessOptions {{
  /** User prompt to send to the agent. */
  prompt: string;
}}

function spawnArgs(o: HarnessOptions): string[] {{
  const a = ["--json"];
  if (o.yolo) a.push("--yolo");
  if (o.model) a.push("--model", o.model);
  if (o.systemPrompt) a.push("--system-prompt", o.systemPrompt);
  if (o.appendSystemPrompt) a.push("--append-system-prompt", o.appendSystemPrompt);
  if (o.args) a.push(...o.args);
  return a;
}}

/** Anonymous per-install id for SDK telemetry — its own id file, distinct
 *  from the harness CLI's install id, so SDK users aren't conflated with
 *  direct CLI users. Only ever leaves the machine when the harness has an
 *  OTLP endpoint configured (OTEL_EXPORTER_OTLP_ENDPOINT); opt out entirely
 *  with GRAFF_NO_TELEMETRY=1 or by passing --no-telemetry in `args`. */
function sdkInstallId(): string {{
  const p = join(homedir(), ".simple-harness-sdk-id");
  try {{
    const v = readFileSync(p, "utf8").trim();
    if (/^[0-9a-f]{{32}}$/.test(v)) return v;
  }} catch {{}}
  const id = randomBytes(16).toString("hex");
  try {{ writeFileSync(p, id + "\\n"); }} catch {{}}
  return id;
}}

/** The CLI is `graff` (renamed from `harness`); prefer it when on PATH,
 *  fall back to the old name so pre-rename installs keep working. */
function defaultBinary(): string {{
  for (const dir of (process.env.PATH ?? "").split(":")) {{
    if (dir && existsSync(join(dir, "graff"))) return "graff";
  }}
  return "harness";
}}

const TELEMETRY_DEFAULT = "https://harness-telemetry.rachpradhan.workers.dev";

/** Best-effort OTLP ERROR log for failures the harness process cannot report
 *  itself (it may be dead or never have started): spawn failures, mid-turn
 *  exits. Same pipeline and opt-out as harness telemetry — skipped when
 *  GRAFF_NO_TELEMETRY is set; endpoint from OTEL_EXPORTER_OTLP_ENDPOINT /
 *  GRAFF_OTEL_ENDPOINT, else the default collector. Fire-and-forget. */
function reportError(kind: string, detail: string): void {{
  if (process.env.GRAFF_NO_TELEMETRY) return;
  const base = (process.env.OTEL_EXPORTER_OTLP_ENDPOINT || process.env.GRAFF_OTEL_ENDPOINT || TELEMETRY_DEFAULT).replace(/\\/+$/, "");
  const url = base.endsWith("/v1/logs") ? base : base + "/v1/logs";
  const payload = JSON.stringify({{ resourceLogs: [{{
    resource: {{ attributes: [
      {{ key: "service.name", value: {{ stringValue: "simple-harness" }} }},
      {{ key: "client.name", value: {{ stringValue: process.env.HARNESS_CLIENT ?? "sdk-ts" }} }},
      {{ key: "sdk.install.id", value: {{ stringValue: sdkInstallId() }} }},
    ] }},
    scopeLogs: [{{ scope: {{ name: "simple-harness-sdk" }}, logRecords: [{{
      timeUnixNano: String(Date.now() * 1e6),
      severityText: "ERROR",
      body: {{ stringValue: "error" }},
      attributes: [
        {{ key: "kind", value: {{ stringValue: kind }} }},
        {{ key: "detail", value: {{ stringValue: detail.slice(0, 512) }} }},
      ],
    }}] }}],
  }}] }});
  try {{
    fetch(url, {{
      method: "POST",
      // default runtime UAs can be bot-blocked by Cloudflare in front of
      // the collector (403) — identify explicitly.
      headers: {{ "content-type": "application/json", "user-agent": "simple-harness-sdk-ts" }},
      body: payload,
      signal: AbortSignal.timeout(3000),
    }}).catch(() => {{}});
  }} catch {{ /* fetch unavailable: drop */ }}
}}

/** Best-effort OTLP "fleet" log for the federated evolution loop (docs §9):
 *  propose / submit / elite_pull signals, tagged by client so CLI/TS/Python
 *  contributions stay distinguishable in /v1/stats. Same opt-out + endpoint as
 *  reportError. Fire-and-forget. */
export function fleetSignal(kind: string, attrs: Record<string, string | number> = {{}}): void {{
  if (process.env.GRAFF_NO_TELEMETRY) return;
  let base = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || process.env.GRAFF_OTEL_ENDPOINT || TELEMETRY_DEFAULT;
  while (base.endsWith("/")) base = base.slice(0, -1);
  const url = base.endsWith("/v1/logs") ? base : base + "/v1/logs";
  const attributes: Array<Record<string, unknown>> = [
    {{ key: "kind", value: {{ stringValue: kind }} }},
  ];
  for (const [k, v] of Object.entries(attrs)) {{
    attributes.push({{ key: k, value: typeof v === "number" ? {{ doubleValue: v }} : {{ stringValue: String(v) }} }});
  }}
  const payload = JSON.stringify({{ resourceLogs: [{{
    resource: {{ attributes: [
      {{ key: "service.name", value: {{ stringValue: "simple-harness" }} }},
      {{ key: "client.name", value: {{ stringValue: process.env.HARNESS_CLIENT ?? "sdk-ts" }} }},
      {{ key: "sdk.install.id", value: {{ stringValue: sdkInstallId() }} }},
    ] }},
    scopeLogs: [{{ scope: {{ name: "simple-harness-sdk" }}, logRecords: [{{
      timeUnixNano: String(Date.now() * 1e6),
      body: {{ stringValue: "fleet" }},
      attributes,
    }}] }}],
  }}] }});
  try {{
    fetch(url, {{
      method: "POST",
      headers: {{ "content-type": "application/json", "user-agent": "simple-harness-sdk-ts" }},
      body: payload,
      signal: AbortSignal.timeout(3000),
    }}).catch(() => {{}});
  }} catch {{ /* fetch unavailable: drop */ }}
}}

/** Spawn env: tag the harness child as SDK-driven for telemetry attribution
 *  (explicit caller values win). The id file is only read/created when
 *  telemetry is actually live — same gating as the harness CLI's own id. */
function sdkEnv(base?: NodeJS.ProcessEnv): NodeJS.ProcessEnv {{
  const env = {{ ...(base ?? process.env) }};
  env.HARNESS_CLIENT ??= "sdk-ts";
  const live = !env.GRAFF_NO_TELEMETRY &&
    (env.OTEL_EXPORTER_OTLP_ENDPOINT || env.GRAFF_OTEL_ENDPOINT);
  if (live && !env.HARNESS_SDK_INSTALL_ID) env.HARNESS_SDK_INSTALL_ID = sdkInstallId();
  return env;
}}

// ── Harness (parallel to codegraff's `Graff`) ──────────────────────────────

/** A live `harness --json` agent. Multi-turn: each `chat()` / `session().send()`
 *  continues the same conversation (the process retains history). */
export class Harness {{
  // stdin/stdout piped, stderr inherited (tool progress straight to the
  // user's terminal) — hence the ByStdio<Writable, Readable, null> shape.
  private proc: ChildProcessByStdio<Writable, Readable, null>;
  private queue: ((e: Event | null) => void)[] = [];
  private buffer: Event[] = [];

  constructor(opts: HarnessOptions = {{}}) {{
    this.proc = spawn(opts.binary ?? defaultBinary(), spawnArgs(opts), {{
      cwd: opts.cwd,
      env: sdkEnv(opts.env),
      stdio: ["pipe", "pipe", "inherit"],
    }});
    const rl = createInterface({{ input: this.proc.stdout }});
    rl.on("line", (line) => {{
      if (!line.trim()) return;
      let ev: Event;
      try {{ ev = JSON.parse(line) as Event; }} catch {{ return; }}
      const w = this.queue.shift();
      if (w) w(ev); else this.buffer.push(ev);
    }});
    this.proc.on("close", () => {{ for (const w of this.queue) w(null); this.queue = []; }});
    // Spawn failures (ENOENT etc.) never emit "close"; report and release
    // any waiters so callers get the mid-turn-death error instead of a hang.
    this.proc.on("error", (e) => {{
      reportError("spawn", String(e));
      for (const w of this.queue) w(null);
      this.queue = [];
    }});
  }}

  /** Start a long-lived agent (codegraff parity for `Graff.init`). */
  static init(opts: HarnessOptions = {{}}): Harness {{ return new Harness(opts); }}

  private next(): Promise<Event | null> {{
    if (this.buffer.length) return Promise.resolve(this.buffer.shift()!);
    return new Promise((resolve) => this.queue.push(resolve));
  }}

  /** Run one turn; async-iterate events up to and including `turn`/`error`. */
  async *chat(input: string | ChatOptions): AsyncGenerator<Event> {{
    const prompt = typeof input === "string" ? input : input.prompt;
    this.proc.stdin.write(JSON.stringify({{ type: "user", text: prompt }}) + "\\n");
    while (true) {{
      const ev = await this.next();
      if (ev === null) {{
        // Process closed without a terminal event: died mid-turn. Reported
        // to telemetry and thrown instead of silently ending the stream.
        reportError("died", `harness exited mid-turn (code=${{this.proc.exitCode}})`);
        throw new Error(`harness exited mid-turn (code=${{this.proc.exitCode}})`);
      }}
      yield ev;
      if (ev.type === "turn" || ev.type === "error") return;
    }}
  }}

  /** Run a turn and return just the final assistant text. */
  async ask(input: string | ChatOptions): Promise<string> {{
    let final = "";
    for await (const ev of this.chat(input)) {{
      if (ev.type === "turn") final = ev.text;
      if (ev.type === "error") throw new Error(ev.message);
    }}
    return final;
  }}
  /** Replace (or with append=true, extend) the system prompt for subsequent
   *  turns. Call between turns; resolves on the harness's ack.
   *
   *  KV-cache warning (Manus context-engineering lessons): the system prompt
   *  heads the cached prefix, so ANY mutation — append included — invalidates
   *  the cache for the whole conversation; the next turn re-reads everything
   *  at full input price. Prefer the spawn-time `systemPrompt` /
   *  `appendSystemPrompt` options; mutate only at task boundaries, never
   *  back-and-forth inside a loop. */
  async setSystemPrompt(text: string, append = false): Promise<void> {{
    this.proc.stdin.write(JSON.stringify({{ type: "set_system_prompt", text, append }}) + "\\n");
    // Edge-version durability: a newer harness may emit event types this
    // client predates — skip them while waiting for the ack (the chat loop
    // already tolerates unknowns the same way) instead of throwing.
    while (true) {{
      const ev = await this.next();
      if (ev === null) {{ reportError("died", "harness closed before acking set_system_prompt"); throw new Error("harness closed"); }}
      if (ev.type === "error") throw new Error(ev.message);
      if (ev.type === "system_prompt") return;
    }}
  }}

  /** Tack extra instructions onto the current system prompt. */
  appendSystemPrompt(text: string): Promise<void> {{ return this.setSystemPrompt(text, true); }}

  /** Record an evaluation score for an agent/prompt variant in the
   *  trajectory archive (harness.trajectory.jsonl) — the DGM evaluation
   *  phase writing back. `promptOrSha` is either the full system-prompt
   *  text (fingerprinted for you) or an existing 16-hex fingerprint.
   *  Pass `parent` (text or sha) when the variant was mutated from another
   *  prompt: that genome-lineage edge is what DGM parent selection counts
   *  children with. Call between turns; resolves on the harness's ack. */
  async score(promptOrSha: string, value: number, notes = "", parent?: string): Promise<void> {{
    const sha = /^[0-9a-f]{{16}}$/.test(promptOrSha) ? promptOrSha : promptFingerprint(promptOrSha);
    const parent_sha = parent === undefined ? undefined
      : /^[0-9a-f]{{16}}$/.test(parent) ? parent : promptFingerprint(parent);
    this.proc.stdin.write(JSON.stringify({{ type: "score", prompt_sha: sha, score: value, notes, parent_sha }}) + "\\n");
    // Same edge-version tolerance as setSystemPrompt: skip unknown events
    // while waiting for the ack.
    while (true) {{
      const ev = await this.next();
      if (ev === null) {{ reportError("died", "harness closed before acking score"); throw new Error("harness closed"); }}
      if (ev.type === "error") throw new Error(ev.message);
      if (ev.type === "score") {{ fleetSignal("submit", {{ prompt_sha: sha, parent_sha: parent_sha ?? "" }}); return; }}
    }}
  }}

  /** Pull the fleet's live champion personas for a model tier (docs §9 Step 2,
   *  GET /v1/elites). Emits a `fleet:elite_pull` signal and returns the elites
   *  (empty when none are promoted yet). Hits the telemetry collector, not the
   *  harness subprocess. */
  async pullElites(providerClass: string, evalSetHash?: string): Promise<Array<Record<string, unknown>>> {{
    let base = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || process.env.GRAFF_OTEL_ENDPOINT || TELEMETRY_DEFAULT;
    while (base.endsWith("/")) base = base.slice(0, -1);
    if (base.endsWith("/v1/logs")) base = base.slice(0, -"/v1/logs".length);
    let q = "provider_class=" + encodeURIComponent(providerClass);
    if (evalSetHash) q += "&eval_set_hash=" + encodeURIComponent(evalSetHash);
    let elites: Array<Record<string, unknown>> = [];
    try {{
      const res = await fetch(base + "/v1/elites?" + q, {{ signal: AbortSignal.timeout(5000) }});
      const j = (await res.json()) as {{ elites?: Array<Record<string, unknown>> }};
      elites = j?.elites ?? [];
    }} catch {{ /* collector unreachable: no elites */ }}
    fleetSignal("elite_pull", {{ provider_class: providerClass, eval_set_hash: evalSetHash ?? "", n_elites: elites.length }});
    return elites;
  }}

  /** A multi-turn session view over this agent (codegraff parity). */
  session(): HarnessSession {{ return new HarnessSession(this); }}


  /** The harness schema version this client was generated from. */
  version(): string {{ return HARNESS_VERSION; }}

  /** Close stdin and give the harness a moment to exit cleanly — it flushes
   *  telemetry and trajectory records on the way out; killing immediately
   *  would race (and lose) that flush. */
  close(): void {{
    this.proc.stdin.end();
    const t = setTimeout(() => this.proc.kill(), 15000);
    t.unref?.();
    this.proc.on("close", () => clearTimeout(t));
  }}
}}

// ── HarnessSession (parallel to codegraff's `GraffSession`) ────────────────

export class HarnessSession {{
  private agent: Harness;
  /** Wrap an existing agent, or spawn a fresh one. */
  constructor(agent: Harness = new Harness()) {{ this.agent = agent; }}
  /** Send a user turn; async-iterate its events. */
  send(input: string | ChatOptions): AsyncGenerator<Event> {{ return this.agent.chat(input); }}
  ask(input: string | ChatOptions): Promise<string> {{ return this.agent.ask(input); }}
  setSystemPrompt(text: string, append = false): Promise<void> {{ return this.agent.setSystemPrompt(text, append); }}
  close(): void {{ this.agent.close(); }}
}}

// ── Top-level one-shot (parallel to codegraff's `runAgent`) ────────────────

/** Spawn an agent, run a single turn, stream its events, then close. */
export async function* runAgent(opts: RunAgentOptions): AsyncGenerator<Event> {{
  const h = new Harness(opts);
  try {{
    yield* h.chat({{ prompt: opts.prompt }});
  }} finally {{
    h.close();
  }}
}}

export const MODELS: ModelName[] = [{", ".join(f'"{m}"' for m in models)}];
export const TOOLS: ToolName[] = [{", ".join(f'"{t}"' for t in tools)}];
'''


def gen_ts_remote(schema):
    """Edge-safe remote client: drives a `harness serve` bridge over fetch +
    Web Streams only — zero node: imports, so it runs on Cloudflare Workers,
    Deno, Bun, browsers, and Node >= 18 alike. Self-contained on purpose
    (its own copy of the generated types): no cross-file imports keeps both
    entry points independently consumable."""
    models = sorted({m["name"] for m in schema["models"]})
    tools = [t["name"] for t in schema["tools"]]
    providers = [p["id"] for p in schema["providers"]]
    version = schema.get("version", "0")
    model_union = " | ".join(f'"{m}"' for m in models)
    tool_union = " | ".join(f'"{t}"' for t in tools)
    provider_union = " | ".join(f'"{p}"' for p in providers)
    header = "// AUTO-GENERATED by sdk/generate.py from `harness --schema`. Do not edit.\n"
    return header + f'''
// Edge-safe remote transport for a `harness serve` bridge: fetch + Web
// Streams only (no node: imports), so it runs on Cloudflare Workers, Deno,
// Bun, browsers, and Node >= 18. The server side is `harness serve`
// (see the "serve" key of `harness --schema`): each session is a real
// `harness --json` child over there, and one POST = one protocol request,
// streamed back as NDJSON until that request's terminal event.

export const HARNESS_VERSION = "{version}";

export type ModelName = {model_union};
export type ToolName = {tool_union};
export type ProviderId = {provider_union};

/** Events streamed by the bridge (same `--json` contract as the stdio SDK).
 *  Forward compatibility: a newer (edge) harness may stream event types not
 *  in this union; every loop here only terminates on its request's terminal
 *  event, so unknown events pass through and are safe to ignore. */
export type Event =
  | {{ type: "text"; text: string }}
  | {{ type: "tool_call"; name: string; input: Record<string, unknown> }}
  | {{ type: "tool_result"; name: string; is_error: boolean; text: string }}
  | {{ type: "turn"; text: string; context_tokens: number; cost_usd: number }}
  | {{ type: "system_prompt"; ok: boolean; append: boolean; chars: number }}
  | {{ type: "score"; ok: boolean; prompt_sha: string }}
  | {{ type: "error"; message: string }};

/** Async (WebCrypto) variant of the trajectory-archive prompt fingerprint:
 *  first 8 bytes of SHA-256, hex (16 chars). */
export async function promptFingerprint(text: string): Promise<string> {{
  const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(d).slice(0, 8)].map((b) => b.toString(16).padStart(2, "0")).join("");
}}

export interface RemoteOptions {{
  /** Base URL of the `harness serve` bridge, e.g. "http://127.0.0.1:8787". */
  url: string;
  /** Bearer token (the bridge's --token / HARNESS_SERVE_TOKEN). */
  token?: string;
  /** Pin the session's model or provider (overrides the serve default). */
  model?: ModelName | ProviderId | string;
  /** Skip every permission prompt server-side (passes --yolo to the child).
   *  Usually what you want: the bridge has no terminal to ask on. */
  yolo?: boolean;
  /** Replace the built-in system prompt. */
  systemPrompt?: string;
  /** Append extra text to the system prompt. */
  appendSystemPrompt?: string;
  /** Attach to an existing session instead of creating one. */
  sessionId?: string;
}}

export interface ChatOptions {{
  prompt: string;
}}

export interface RunAgentRemoteOptions extends RemoteOptions {{
  prompt: string;
}}

/** Parse a streaming NDJSON response body into events. */
async function* ndjson(res: Response): AsyncGenerator<Event> {{
  const body = res.body;
  if (!body) throw new Error("bridge response had no body");
  const reader = body.getReader();
  const dec = new TextDecoder();
  let buf = "";
  while (true) {{
    const {{ done, value }} = await reader.read();
    if (done) break;
    buf += dec.decode(value, {{ stream: true }});
    let i: number;
    while ((i = buf.indexOf("\\n")) >= 0) {{
      const line = buf.slice(0, i).trim();
      buf = buf.slice(i + 1);
      if (line) {{ try {{ yield JSON.parse(line) as Event; }} catch {{ /* skip noise */ }} }}
    }}
  }}
  const tail = buf.trim();
  if (tail) {{ try {{ yield JSON.parse(tail) as Event; }} catch {{ /* skip noise */ }} }}
}}

const HEX16 = /^[0-9a-f]{{16}}$/;

/** A session on a remote `harness serve` bridge — the fetch-transport
 *  analogue of the stdio `Harness` class, same method surface. */
export class RemoteHarness {{
  private base: string;
  private token?: string;
  /** Resolves to the session id (creation is lazy-started in the constructor). */
  readonly sessionId: Promise<string>;

  constructor(opts: RemoteOptions) {{
    this.base = opts.url.replace(/\\/+$/, "");
    this.token = opts.token;
    this.sessionId = opts.sessionId
      ? Promise.resolve(opts.sessionId)
      : this.create(opts);
  }}

  /** Create a session (codegraff parity for `Graff.init`, remote edition). */
  static init(opts: RemoteOptions): RemoteHarness {{ return new RemoteHarness(opts); }}

  private headers(): Record<string, string> {{
    const h: Record<string, string> = {{ "content-type": "application/json" }};
    if (this.token) h.authorization = `Bearer ${{this.token}}`;
    return h;
  }}

  private async req(method: string, path: string, body?: unknown): Promise<Response> {{
    const res = await fetch(this.base + path, {{
      method,
      headers: this.headers(),
      body: body === undefined ? undefined : JSON.stringify(body),
    }});
    if (!res.ok) {{
      const detail = await res.text().catch(() => "");
      throw new Error(`bridge ${{method}} ${{path}} → ${{res.status}}: ${{detail.slice(0, 256)}}`);
    }}
    return res;
  }}

  private async create(opts: RemoteOptions): Promise<string> {{
    const body: Record<string, unknown> = {{}};
    if (opts.model) body.model = opts.model;
    if (opts.yolo !== undefined) body.yolo = opts.yolo;
    if (opts.systemPrompt) body.system_prompt = opts.systemPrompt;
    if (opts.appendSystemPrompt) body.append_system_prompt = opts.appendSystemPrompt;
    const res = await this.req("POST", "/v1/sessions", body);
    const data = (await res.json()) as {{ session_id: string }};
    return data.session_id;
  }}

  /** Send one protocol request; stream its events. */
  private async *send(payload: Record<string, unknown>): AsyncGenerator<Event> {{
    const id = await this.sessionId;
    const res = await this.req("POST", `/v1/sessions/${{id}}`, payload);
    yield* ndjson(res);
  }}

  /** Run one turn; async-iterate events up to and including `turn`/`error`. */
  async *chat(input: string | ChatOptions): AsyncGenerator<Event> {{
    const prompt = typeof input === "string" ? input : input.prompt;
    let terminal = false;
    for await (const ev of this.send({{ type: "user", text: prompt }})) {{
      yield ev;
      if (ev.type === "turn" || ev.type === "error") {{ terminal = true; break; }}
    }}
    if (!terminal) throw new Error("bridge stream ended mid-turn (session process died?)");
  }}

  /** Run a turn and return just the final assistant text. */
  async ask(input: string | ChatOptions): Promise<string> {{
    let final = "";
    for await (const ev of this.chat(input)) {{
      if (ev.type === "turn") final = ev.text;
      if (ev.type === "error") throw new Error(ev.message);
    }}
    return final;
  }}

  /** Replace (or with append=true, extend) the system prompt for later turns.
   *  Same KV-cache warning as the stdio SDK: any mutation invalidates the
   *  cached prefix for the whole conversation — prefer the creation-time
   *  options; mutate only at task boundaries. */
  async setSystemPrompt(text: string, append = false): Promise<void> {{
    for await (const ev of this.send({{ type: "set_system_prompt", text, append }})) {{
      if (ev.type === "error") throw new Error(ev.message);
      if (ev.type === "system_prompt") return;
    }}
    throw new Error("bridge stream ended before acking set_system_prompt");
  }}

  appendSystemPrompt(text: string): Promise<void> {{ return this.setSystemPrompt(text, true); }}

  /** Record an evaluation score in the server-side trajectory archive —
   *  same semantics as the stdio SDK's `score()`. */
  async score(promptOrSha: string, value: number, notes = "", parent?: string): Promise<void> {{
    const sha = HEX16.test(promptOrSha) ? promptOrSha : await promptFingerprint(promptOrSha);
    const parent_sha = parent === undefined ? undefined
      : HEX16.test(parent) ? parent : await promptFingerprint(parent);
    for await (const ev of this.send({{ type: "score", prompt_sha: sha, score: value, notes, parent_sha }})) {{
      if (ev.type === "error") throw new Error(ev.message);
      if (ev.type === "score") return;
    }}
    throw new Error("bridge stream ended before acking score");
  }}

  /** The harness schema version this client was generated from. */
  version(): string {{ return HARNESS_VERSION; }}

  /** Close the remote session (graceful: the bridge EOFs the child's stdin
   *  so it flushes telemetry/trajectory on the way out). */
  async close(): Promise<void> {{
    const id = await this.sessionId;
    await this.req("DELETE", `/v1/sessions/${{id}}`).catch(() => {{}});
  }}
}}

/** Create a remote session, run a single turn, stream its events, close. */
export async function* runAgentRemote(opts: RunAgentRemoteOptions): AsyncGenerator<Event> {{
  const h = new RemoteHarness(opts);
  try {{
    yield* h.chat({{ prompt: opts.prompt }});
  }} finally {{
    await h.close();
  }}
}}

export const MODELS: ModelName[] = [{", ".join(f'"{m}"' for m in models)}];
export const TOOLS: ToolName[] = [{", ".join(f'"{t}"' for t in tools)}];
'''


def gen_py(schema):
    models = sorted({m["name"] for m in schema["models"]})
    tools = [t["name"] for t in schema["tools"]]
    providers = [p["id"] for p in schema["providers"]]
    header = '"""AUTO-GENERATED by sdk/generate.py from `harness --schema`. Do not edit."""\n'
    return header + f'''from __future__ import annotations
import hashlib
import hmac
import json
import os
import re
import secrets
import subprocess
import threading
import time
import urllib.error
import urllib.request
from typing import Iterator, Optional

MODELS = {json.dumps(models)}
TOOLS = {json.dumps(tools)}
PROVIDERS = {json.dumps(providers)}


def _sdk_install_id() -> str:
    """Anonymous per-install id for SDK telemetry — its own id file, distinct
    from the harness CLI's install id, so SDK users are counted separately.
    Only ever leaves the machine when the harness has an OTLP endpoint
    configured (OTEL_EXPORTER_OTLP_ENDPOINT); opt out entirely with
    GRAFF_NO_TELEMETRY=1 or by passing --no-telemetry in `args`."""
    path = os.path.join(os.path.expanduser("~"), ".simple-harness-sdk-id")
    try:
        with open(path) as f:
            v = f.read().strip()
        if len(v) == 32 and all(c in "0123456789abcdef" for c in v):
            return v
    except OSError:
        pass
    v = secrets.token_hex(16)
    try:
        with open(path, "w") as f:
            f.write(v + "\\n")
    except OSError:
        pass
    return v


def _default_binary() -> str:
    """The CLI is `graff` (renamed from `harness`); prefer it when on PATH,
    fall back to the old name so pre-rename installs keep working."""
    import shutil
    return "graff" if shutil.which("graff") else "harness"


_TELEMETRY_DEFAULT = "https://harness-telemetry.rachpradhan.workers.dev"


def _report_error(kind: str, detail: str) -> None:
    """Best-effort OTLP ERROR log for failures the harness process cannot
    report itself (it may be dead or never have started): spawn failures,
    mid-turn exits, protocol breaks. Same pipeline and opt-out as harness
    telemetry — skipped when GRAFF_NO_TELEMETRY is set; endpoint from
    OTEL_EXPORTER_OTLP_ENDPOINT / GRAFF_OTEL_ENDPOINT, else the default
    collector. Fire-and-forget on a daemon thread; never raises."""
    if os.environ.get("GRAFF_NO_TELEMETRY"):
        return
    base = (os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT")
            or os.environ.get("GRAFF_OTEL_ENDPOINT")
            or _TELEMETRY_DEFAULT).rstrip("/")
    url = base if base.endswith("/v1/logs") else base + "/v1/logs"
    payload = json.dumps({{"resourceLogs": [{{
        "resource": {{"attributes": [
            {{"key": "service.name", "value": {{"stringValue": "simple-harness"}}}},
            {{"key": "client.name", "value": {{"stringValue": os.environ.get("HARNESS_CLIENT", "sdk-py")}}}},
            {{"key": "sdk.install.id", "value": {{"stringValue": _sdk_install_id()}}}},
        ]}},
        "scopeLogs": [{{"scope": {{"name": "simple-harness-sdk"}}, "logRecords": [{{
            "timeUnixNano": str(int(time.time() * 1e9)),
            "severityText": "ERROR",
            "body": {{"stringValue": "error"}},
            "attributes": [
                {{"key": "kind", "value": {{"stringValue": kind}}}},
                {{"key": "detail", "value": {{"stringValue": detail[:512]}}}},
            ],
        }}]}}],
    }}]}}).encode()

    def post():
        try:
            req = urllib.request.Request(
                url, data=payload, headers={{
                    "Content-Type": "application/json",
                    # urllib's default Python-urllib/x.y UA is bot-blocked by
                    # Cloudflare in front of the collector (403) — identify.
                    "User-Agent": "simple-harness-sdk-py",
                }})
            urllib.request.urlopen(req, timeout=3).read()
        except Exception:
            pass
    threading.Thread(target=post, daemon=True).start()


def _fleet_signal(kind: str, attrs: Optional[dict] = None) -> None:
    """Best-effort OTLP "fleet" log for the federated evolution loop (docs §9):
    propose / submit / elite_pull signals, tagged by client so CLI/TS/Python
    contributions stay distinguishable in /v1/stats. Same opt-out + endpoint as
    _report_error. Fire-and-forget on a daemon thread; never raises."""
    if os.environ.get("GRAFF_NO_TELEMETRY"):
        return
    base = (os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT")
            or os.environ.get("GRAFF_OTEL_ENDPOINT")
            or _TELEMETRY_DEFAULT).rstrip("/")
    url = base if base.endswith("/v1/logs") else base + "/v1/logs"
    al = [{{"key": "kind", "value": {{"stringValue": kind}}}}]
    for k, v in (attrs or {{}}).items():
        val = {{"doubleValue": v}} if isinstance(v, (int, float)) else {{"stringValue": str(v)}}
        al.append({{"key": k, "value": val}})
    payload = json.dumps({{"resourceLogs": [{{
        "resource": {{"attributes": [
            {{"key": "service.name", "value": {{"stringValue": "simple-harness"}}}},
            {{"key": "client.name", "value": {{"stringValue": os.environ.get("HARNESS_CLIENT", "sdk-py")}}}},
            {{"key": "sdk.install.id", "value": {{"stringValue": _sdk_install_id()}}}},
        ]}},
        "scopeLogs": [{{"scope": {{"name": "simple-harness-sdk"}}, "logRecords": [{{
            "timeUnixNano": str(int(time.time() * 1e9)),
            "body": {{"stringValue": "fleet"}},
            "attributes": al,
        }}]}}],
    }}]}}).encode()

    def post():
        try:
            req = urllib.request.Request(
                url, data=payload, headers={{
                    "Content-Type": "application/json",
                    "User-Agent": "simple-harness-sdk-py",
                }})
            urllib.request.urlopen(req, timeout=3).read()
        except Exception:
            pass
    threading.Thread(target=post, daemon=True).start()


def prompt_fingerprint(text: str) -> str:
    """Fingerprint of a system prompt as used in harness.trajectory.jsonl —
    the append-only DGM-style archive — and by `Harness.score()`:
    first 8 bytes of SHA-256, hex (16 chars)."""
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def score_signature(key: bytes, prompt_sha: str, parent_sha: str, score: float,
                    run_id: str, judge_id: str = "", artifact_sha: str = "",
                    eval_set_hash: str = "") -> str:
    """Recompute a score record's HMAC the way the harness signs it (Step 0,
    fitness-channel integrity). The canonical message is version-tagged and
    newline-joined with the score fixed to 6 decimals — byte-identical to the
    Zig signer (src/main.zig scoreSigMessage). `key` is the raw bytes of the
    GRAFF_SCORE_KEY_FILE file."""
    msg = "v1\\n{{}}\\n{{}}\\n{{:.6f}}\\n{{}}\\n{{}}\\n{{}}\\n{{}}".format(
        prompt_sha, parent_sha, score, run_id, judge_id, artifact_sha, eval_set_hash)
    return hmac.new(key, msg.encode(), hashlib.sha256).hexdigest()


def verify_score(key: bytes, rec: dict) -> bool:
    """True iff a kind:"score" trajectory/D1 record carries a valid signature
    for `key`. Use this in an evolution driver's archive loader to reject
    forged fitness rows (an attacker without the key cannot produce a matching
    sig). Records with no sig fail closed when a key is set."""
    sig = rec.get("sig") or ""
    if not sig:
        return False
    want = score_signature(
        key, rec.get("prompt_sha", ""), rec.get("parent_sha", "") or "",
        float(rec.get("score", "nan")), rec.get("run_id", ""),
        rec.get("judge_id", ""), rec.get("artifact_sha", ""),
        rec.get("eval_set_hash", ""))
    return hmac.compare_digest(sig, want)

class Harness:
    """Drives a `harness --json` subprocess. One turn = send text, stream events.

    Events are plain dicts with a "type" field: "text", "tool_call",
    "tool_result", "turn", or "error" (see the harness --schema protocol).
    """

    def __init__(self, binary: Optional[str] = None, args: Optional[list] = None,
                 cwd: Optional[str] = None, env: Optional[dict] = None,
                 model: Optional[str] = None, yolo: bool = False,
                 system_prompt: Optional[str] = None,
                 append_system_prompt: Optional[str] = None):
        binary = binary or _default_binary()
        argv = [binary, "--json"]
        if yolo:
            argv.append("--yolo")
        if model:
            argv += ["--model", model]
        if system_prompt:
            argv += ["--system-prompt", system_prompt]
        if append_system_prompt:
            argv += ["--append-system-prompt", append_system_prompt]
        argv += list(args or [])
        # Tag the harness child as SDK-driven for telemetry attribution
        # (explicit caller values win). The id file is only read/created when
        # telemetry is actually live — same gating as the harness CLI's own id.
        run_env = dict(env if env is not None else os.environ)
        run_env.setdefault("HARNESS_CLIENT", "sdk-py")
        live = not run_env.get("GRAFF_NO_TELEMETRY") and (
            run_env.get("OTEL_EXPORTER_OTLP_ENDPOINT") or run_env.get("GRAFF_OTEL_ENDPOINT"))
        if live and "HARNESS_SDK_INSTALL_ID" not in run_env:
            run_env["HARNESS_SDK_INSTALL_ID"] = _sdk_install_id()
        try:
            self.proc = subprocess.Popen(
                argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                text=True, bufsize=1, cwd=cwd, env=run_env,
            )
        except OSError as e:
            _report_error("spawn", f"{{binary}}: {{e}}")
            raise

    def chat(self, text: str) -> Iterator[dict]:
        """Send a user turn; yield events until (and including) the 'turn'
        event. Raises RuntimeError (after reporting to telemetry) if the
        harness process dies mid-turn instead of silently yielding nothing."""
        assert self.proc.stdin and self.proc.stdout
        try:
            self.proc.stdin.write(json.dumps({{"type": "user", "text": text}}) + "\\n")
            self.proc.stdin.flush()
        except OSError as e:
            _report_error("died", f"harness pipe closed on send: {{e}}")
            raise
        for line in self.proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue
            yield ev
            if ev.get("type") in ("turn", "error"):
                return
        # stdout EOF without a terminal event: the harness died mid-turn.
        rc = self.proc.poll()
        _report_error("died", f"harness exited mid-turn (rc={{rc}})")
        raise RuntimeError(f"harness exited mid-turn (rc={{rc}})")

    def ask(self, text: str) -> str:
        """Run a turn and return just the final assistant text."""
        final = ""
        for ev in self.chat(text):
            if ev.get("type") == "turn":
                final = ev["text"]
            elif ev.get("type") == "error":
                raise RuntimeError(ev["message"])
        return final

    def set_system_prompt(self, text: str, append: bool = False) -> None:
        """Replace (or with append=True, extend) the system prompt for later
        turns. Call between turns; blocks until the harness acks.

        KV-cache warning (Manus context-engineering lessons): the system
        prompt heads the cached prefix, so ANY mutation — append included —
        invalidates the cache for the whole conversation; the next turn
        re-reads everything at full input price. Prefer the spawn-time
        system_prompt/append_system_prompt arguments; mutate only at task
        boundaries, never back-and-forth inside a loop."""
        assert self.proc.stdin and self.proc.stdout
        self.proc.stdin.write(json.dumps(
            {{"type": "set_system_prompt", "text": text, "append": append}}) + "\\n")
        self.proc.stdin.flush()
        for line in self.proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue
            if ev.get("type") == "error":
                raise RuntimeError(ev["message"])
            if ev.get("type") == "system_prompt":
                return
        _report_error("died", f"harness closed before acking set_system_prompt (rc={{self.proc.poll()}})")
        raise RuntimeError("harness closed before acking set_system_prompt")

    def append_system_prompt(self, text: str) -> None:
        """Tack extra instructions onto the current system prompt."""
        self.set_system_prompt(text, append=True)

    def score(self, prompt_or_sha: str, value: float, notes: str = "",
              parent: Optional[str] = None, judge_id: str = "",
              artifact_sha: str = "", eval_set_hash: str = "") -> None:
        """Record an evaluation score for an agent/prompt variant in the
        trajectory archive (harness.trajectory.jsonl) — the DGM evaluation
        phase writing back. `prompt_or_sha` is either the full system-prompt
        text (fingerprinted for you) or an existing 16-hex fingerprint.
        Pass `parent` (text or sha) when the variant was mutated from
        another prompt: that genome-lineage edge is what DGM parent
        selection counts children with.

        Provenance (signed when GRAFF_SCORE_KEY_FILE is set): `judge_id`
        names the evaluator, `artifact_sha` the thing it judged, and
        `eval_set_hash` the held-out eval used — all folded into the record's
        HMAC so a forged fitness row is detectable (see `verify_score`).
        Call between turns; blocks until the harness acks."""
        assert self.proc.stdin and self.proc.stdout
        sha = prompt_or_sha if re.fullmatch(r"[0-9a-f]{{16}}", prompt_or_sha) \\
            else prompt_fingerprint(prompt_or_sha)
        req = {{"type": "score", "prompt_sha": sha, "score": value, "notes": notes}}
        if parent is not None:
            req["parent_sha"] = parent if re.fullmatch(r"[0-9a-f]{{16}}", parent) \\
                else prompt_fingerprint(parent)
        if judge_id:
            req["judge_id"] = judge_id
        if artifact_sha:
            req["artifact_sha"] = artifact_sha
        if eval_set_hash:
            req["eval_set_hash"] = eval_set_hash
        self.proc.stdin.write(json.dumps(req) + "\\n")
        self.proc.stdin.flush()
        for line in self.proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue
            if ev.get("type") == "error":
                raise RuntimeError(ev["message"])
            if ev.get("type") == "score":
                _fleet_signal("submit", {{"prompt_sha": sha, "eval_set_hash": eval_set_hash}})
                return
        _report_error("died", f"harness closed before acking score (rc={{self.proc.poll()}})")
        raise RuntimeError("harness closed before acking score")

    def pull_elites(self, provider_class: str, eval_set_hash: str = "") -> list:
        """Pull the fleet's live champion personas for a model tier (docs §9
        Step 2, GET /v1/elites). Emits a `fleet:elite_pull` signal and returns
        the elites list (empty when none are promoted yet). Hits the telemetry
        collector, not the harness subprocess."""
        base = (os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT")
                or os.environ.get("GRAFF_OTEL_ENDPOINT")
                or _TELEMETRY_DEFAULT).rstrip("/")
        if base.endswith("/v1/logs"):
            base = base[: -len("/v1/logs")]
        q = "provider_class=" + provider_class
        if eval_set_hash:
            q += "&eval_set_hash=" + eval_set_hash
        elites: list = []
        try:
            req = urllib.request.Request(
                base + "/v1/elites?" + q,
                headers={{"User-Agent": "simple-harness-sdk-py"}})
            body = urllib.request.urlopen(req, timeout=5).read()
            elites = (json.loads(body) or {{}}).get("elites", []) or []
        except Exception:
            pass
        _fleet_signal("elite_pull", {{"provider_class": provider_class,
                                      "eval_set_hash": eval_set_hash,
                                      "n_elites": len(elites)}})
        return elites
    def close(self):
        """Close stdin and give the harness a moment to exit cleanly — it
        flushes telemetry and trajectory records on the way out; killing it
        immediately would race (and lose) that flush."""
        if self.proc.stdin:
            self.proc.stdin.close()
        try:
            self.proc.wait(timeout=15)
        except subprocess.TimeoutExpired:
            self.proc.terminate()

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()


class RemoteHarness:
    """Drives a session on a remote `harness serve` bridge over HTTP — the
    network-transport analogue of `Harness`, same method surface. The server
    side runs `harness serve` (see the "serve" key of `harness --schema`);
    each session is a real `harness --json` child over there, and one POST =
    one protocol request, streamed back as NDJSON until its terminal event.

    Stdlib-only (urllib): usable anywhere Python runs, no local binary
    needed. Pass yolo=True in most cases — the bridge has no terminal to
    show permission prompts on."""

    def __init__(self, url: str, token: Optional[str] = None,
                 model: Optional[str] = None, yolo: bool = False,
                 system_prompt: Optional[str] = None,
                 append_system_prompt: Optional[str] = None,
                 session_id: Optional[str] = None):
        self.base = url.rstrip("/")
        self.token = token
        if session_id is not None:
            self.session_id = session_id
            return
        opts = {{}}
        if model:
            opts["model"] = model
        if yolo:
            opts["yolo"] = True
        if system_prompt:
            opts["system_prompt"] = system_prompt
        if append_system_prompt:
            opts["append_system_prompt"] = append_system_prompt
        resp = self._request("POST", "/v1/sessions", opts)
        self.session_id = json.loads(resp.read())["session_id"]

    def _request(self, method: str, path: str, body=None):
        headers = {{"Content-Type": "application/json",
                   "User-Agent": "simple-harness-sdk-py"}}
        if self.token:
            headers["Authorization"] = "Bearer " + self.token
        data = None if body is None else json.dumps(body).encode()
        req = urllib.request.Request(self.base + path, data=data,
                                     headers=headers, method=method)
        try:
            return urllib.request.urlopen(req)
        except urllib.error.HTTPError as e:
            detail = e.read().decode(errors="replace")[:256]
            raise RuntimeError(f"bridge {{method}} {{path}} → {{e.code}}: {{detail}}") from None

    def _send(self, payload: dict) -> Iterator[dict]:
        """POST one protocol request; yield its streamed NDJSON events."""
        resp = self._request("POST", f"/v1/sessions/{{self.session_id}}", payload)
        for line in resp:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue

    def chat(self, text: str) -> Iterator[dict]:
        """Send a user turn; yield events until (and including) the 'turn'
        event. Raises RuntimeError if the stream ends without one (the
        session process died server-side)."""
        terminal = False
        for ev in self._send({{"type": "user", "text": text}}):
            yield ev
            if ev.get("type") in ("turn", "error"):
                terminal = True
                return
        if not terminal:
            raise RuntimeError("bridge stream ended mid-turn (session process died?)")

    def ask(self, text: str) -> str:
        """Run a turn and return just the final assistant text."""
        final = ""
        for ev in self.chat(text):
            if ev.get("type") == "turn":
                final = ev["text"]
            elif ev.get("type") == "error":
                raise RuntimeError(ev["message"])
        return final

    def set_system_prompt(self, text: str, append: bool = False) -> None:
        """Replace (or with append=True, extend) the system prompt for later
        turns. Same KV-cache warning as `Harness.set_system_prompt`: prefer
        the creation-time arguments; mutate only at task boundaries."""
        for ev in self._send({{"type": "set_system_prompt", "text": text, "append": append}}):
            if ev.get("type") == "error":
                raise RuntimeError(ev["message"])
            if ev.get("type") == "system_prompt":
                return
        raise RuntimeError("bridge stream ended before acking set_system_prompt")

    def append_system_prompt(self, text: str) -> None:
        """Tack extra instructions onto the current system prompt."""
        self.set_system_prompt(text, append=True)

    def score(self, prompt_or_sha: str, value: float, notes: str = "",
              parent: Optional[str] = None, judge_id: str = "",
              artifact_sha: str = "", eval_set_hash: str = "") -> None:
        """Record an evaluation score in the server-side trajectory archive —
        same semantics (and provenance fields) as `Harness.score`."""
        sha = prompt_or_sha if re.fullmatch(r"[0-9a-f]{{16}}", prompt_or_sha) \\
            else prompt_fingerprint(prompt_or_sha)
        req = {{"type": "score", "prompt_sha": sha, "score": value, "notes": notes}}
        if parent is not None:
            req["parent_sha"] = parent if re.fullmatch(r"[0-9a-f]{{16}}", parent) \\
                else prompt_fingerprint(parent)
        if judge_id:
            req["judge_id"] = judge_id
        if artifact_sha:
            req["artifact_sha"] = artifact_sha
        if eval_set_hash:
            req["eval_set_hash"] = eval_set_hash
        for ev in self._send(req):
            if ev.get("type") == "error":
                raise RuntimeError(ev["message"])
            if ev.get("type") == "score":
                return
        raise RuntimeError("bridge stream ended before acking score")

    def close(self):
        """Close the remote session (graceful: the bridge EOFs the child's
        stdin so it flushes telemetry/trajectory on the way out)."""
        try:
            self._request("DELETE", f"/v1/sessions/{{self.session_id}}").read()
        except (RuntimeError, OSError):
            pass

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()
'''


def main():
    schema = load_schema(sys.argv[1:])
    print(f"generating SDKs from schema: {schema.get('harness')} v{schema.get('version')} "
          f"({len(schema['models'])} models, {len(schema['tools'])} tools)")
    write(os.path.join(HERE, "ts", "harness.ts"), gen_ts(schema))
    write(os.path.join(HERE, "ts", "remote.ts"), gen_ts_remote(schema))
    write(os.path.join(HERE, "py", "harness_sdk.py"), gen_py(schema))
    print("done.")


if __name__ == "__main__":
    main()
