//! First-run install of the `codegraff` launcher command (VS Code `code`-style).
//!
//! Writes a small shell script onto the user's PATH so `codegraff <path>` opens
//! that folder in the Codegraff desktop app, and bare `codegraff` opens the app.
//! The script launches this app's own binary detached; the single-instance
//! plugin forwards the path to an already-running window (see `lib.rs`).
//!
//! Best-effort by design: it never fails app startup, and is a no-op in dev
//! (it only acts for an installed `.app` bundle). Prefers `/usr/local/bin`,
//! falling back to `~/.local/bin` when that isn't writable.

#[cfg(target_os = "macos")]
pub fn ensure_cli_symlink(app: &tauri::App) {
    use std::io::Write;
    use std::os::unix::fs::PermissionsExt;
    use std::path::PathBuf;
    use tauri::Manager;

    // …/Codegraff.app/Contents/MacOS/codegraff-gui — the binary the launcher runs.
    let exe = match std::env::current_exe() {
        Ok(p) => p,
        Err(_) => return,
    };
    // Only install from a real bundle; skip `cargo tauri dev` runs out of target/.
    if !exe.to_string_lossy().contains(".app/Contents/MacOS/") {
        return;
    }

    // `code`-style launcher. Resolves the first arg to an absolute path and
    // launches the app detached (nohup + &) so the terminal returns immediately.
    let script = format!(
        "#!/bin/sh\n\
         # codegraff — open a path in the Codegraff desktop app (code-style).\n\
         # Auto-generated by Codegraff on launch; safe to delete.\n\
         APP_BIN=\"{exe}\"\n\
         if [ \"$#\" -eq 0 ]; then\n\
         \x20 nohup \"$APP_BIN\" >/dev/null 2>&1 &\n\
         \x20 exit 0\n\
         fi\n\
         target=\"$1\"\n\
         if [ -e \"$target\" ]; then\n\
         \x20 target=\"$(cd \"$(dirname \"$target\")\" 2>/dev/null && pwd)/$(basename \"$target\")\"\n\
         fi\n\
         nohup \"$APP_BIN\" \"$target\" >/dev/null 2>&1 &\n",
        exe = exe.display()
    );

    let mut targets: Vec<PathBuf> = vec![PathBuf::from("/usr/local/bin")];
    if let Ok(home) = app.path().home_dir() {
        targets.push(home.join(".local").join("bin"));
    }

    for dir in targets {
        let link = dir.join("codegraff");
        // Already current (handles app moves and the prior symlink form)?
        if let Ok(existing) = std::fs::read_to_string(&link) {
            if existing == script {
                log::info!("codegraff launcher already current at {}", link.display());
                return;
            }
        }
        if std::fs::create_dir_all(&dir).is_err() {
            continue;
        }
        // Clear any stale file/symlink (e.g. the 0.0.11 binary symlink).
        let _ = std::fs::remove_file(&link);
        let written = (|| -> std::io::Result<()> {
            let mut f = std::fs::File::create(&link)?;
            f.write_all(script.as_bytes())?;
            f.set_permissions(std::fs::Permissions::from_mode(0o755))?;
            Ok(())
        })();
        match written {
            Ok(()) => {
                log::info!("codegraff launcher installed at {}", link.display());
                return;
            }
            Err(err) => {
                log::warn!("could not write codegraff launcher into {}: {err}", dir.display());
            }
        }
    }
}

#[cfg(not(target_os = "macos"))]
pub fn ensure_cli_symlink(_app: &tauri::App) {}
